### ISSUE TITLE
Permission issues in mysql - container crashing

### ISSUE THREAD

**Issue by gabrielgomessds** [docker-library/mysql#1006]
I've been having this problem for a week and I don't know how to solve it. I started a small laravel project with Docker and Docker's mysql doesn't work at all. It keeps crashing on its own, when running docker logs my-container, I get these errors: **Unable to change permissions for file 'private_key.pem.temp' (OS errno 1 - Operation not permitted)**

My settings: .env:
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=laravel_ead
DB_USERNAME=sail
DB_PASSWORD=root
```

Docker-compose.yml:
```
mysql:
           image: mysql:8.0
           restart: unless-stopped
           environment:
               MYSQL_DATABASE: ${DB_DATABASE}
               MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
               MYSQL_PASSWORD: ${DB_PASSWORD}
               MYSQL_USER: ${DB_USERNAME}
           command: ["--disable-partition-engine-check"]
           volumes:
               - ./.docker/mysql/dbdata:/var/lib/mysql
                 - mysql-data:/var/lib/mysql
           ports:
               - 3388:3306
           networks:
               - laravel-eti
```

I've tried changing the ports, I've tried changing the DB_HOST to 127.0.0.1 for localhost, I've tried clearing the cache, I've installed and tried using Sail, I've tried deleting the entire project and starting over, I've uninstalled and reinstalled docker, I've changed the version of mysql I started with 5.7 and I'm using 8.0 and it seems that this has made the situation worse. I'm using Windows (wsl2). Before I got this error every time I ran php Crafter Migrate - error: **SQLSTATE[HY000][1130] Host '172.20.0.6' does not have permission to connect to this MySQL server.** I am using windows 10 with WSL2
