### ISSUE TITLE
Mysql database not getting created on docker-compose up

### ISSUE THREAD

**Issue by sameerr25** [docker-library/mysql#101]
I have this setup in my docker-compose.yml -
```
db:
  image: mysql:5.7.5
  environment:
    MYSQL_ROOT_PASSWORD: xxxxxx
    MYSQL_DATABASE: development_db
  volumes:
    - /var/lib/mysql
  ports:
    - "3306:3306"
```

But `docker-compose up` is not creating the DB `development_db` in MySQL container.
Anything I could be doing incorrectly?
