### ISSUE TITLE
Cannot connect to local MySQL server in docker container with django

### ISSUE THREAD

**Issue by xiaoweiweizheng** [docker-library/mysql#1012]
I am building a django project in docker with mysql. However, I met some errors.

Here is my docker-compose.yaml file:
```
version: "3"
services:
  mysql8:
    platform: linux/amd64
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /usr/local/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 

  twitter:
    container_name: twitter
    image: xiaowei/django-twitter
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
```
And my Makefile:
```
NAME = xiaowei/django-twitter

.PHONY: build up stop logs

build:  docker-build
up: docker-compose-up
stop: docker-compose-stop
logs: docker-compose-logs

docker-build:
	docker build -t "${NAME}" .

docker-compose-up:
	docker-compose up -d

docker-compose-stop:
	docker-compose stop

docker-compose-logs:
	docker-compose logs --tail=100 -f
```
My Dockerfile:
```
FROM python:3.10-buster
RUN /usr/local/bin/python -m pip install --upgrade pip -i https://mirrors.aliyun.com/pypi/simple
RUN mkdir /code
WORKDIR /code
COPY requirements-prd.txt /code/
RUN pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements-prd.txt
COPY . /code/
```
The corresponding requirements-prd.txt:
```
Django==3.1.3
pymysql
mysqlclient
mysql-connector-python
```

I created the django project by the command: `django-admin startproject django_twitter .`
The corresponding contents in settings.py:
```
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', '192.168.31.59', 'localhost']
...

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': 'localhost',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '123456', 
    }
}
```
However, when I tried to run the django project by command `make build && make up && make logs`, here is the error:
```
 The above exception was the direct cause of the following exception:
twitter   | 
twitter   | Traceback (most recent call last):
twitter   |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
...
twitter   |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/__init__.py", line 121, in Connect
twitter   |     return Connection(*args, **kwargs)
twitter   |   File "/usr/local/lib/python3.10/site-packages/MySQLdb/connections.py", line 193, in __init__
twitter   |     super().__init__(*args, **kwargs2)
twitter   | django.db.utils.OperationalError: (2002, "Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)")
```

I tried to change the host in settings.py to "mysql8", th error became `django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'mysql8' (115)")`

I am an amateur of docker, mysql and django. Not sure if my configuration is not correct.
My laptop is Apple M1 Pro chip in macOS Monterey 12.5, not sure if it is related to the chip.
Thank you for the help!

**Comment by LaurentGoderre** [comment]
The `HOST` in your django config is incorrect because localhost refers to the container itself, not the host where docker runs. You should explicitly link the containers and use the service name of the db (`mysql8` in your case) asd the host. Docker compose adds hostname to the containers to allow them to communicate togheter.

So:

```yaml
version: "3"
services:
  mysql8:
    platform: linux/amd64
    container_name: mysql8
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - /usr/local/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456 

  twitter:
    container_name: twitter
    image: xiaowei/django-twitter
    ports:
      - "8000:8000"
     links:
      - mysql8
    command: python manage.py runserver 0.0.0.0:8000
```

And

```
DEBUG = True
ALLOWED_HOSTS = ['127.0.0.1', '192.168.31.59', 'localhost']
...

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'twitter',
        'HOST': 'mysql8',
        'PORT': '3306',
        'USER': 'root',
        'PASSWORD': '123456', 
    }
}
```
