### ISSUE TITLE
MySQL Server 9.1.0-1.el9 with docker mysql:latest is no longer starting

### ISSUE THREAD

**Issue by Adandu** [docker-library/mysql#1092]
Hello,

I am seeing the below error and MySQL is not starting.

```
024-10-18 12:55:51+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 9.1.0-1.el9 started.

2024-10-18 12:55:51+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config

	command was: mysqld --verbose --help --log-bin-index=/tmp/tmp.xpO6wtikXP

	2024-10-18T12:55:51Z UTC - mysqld got signal 11 ;

Signal SIGSEGV (Address not mapped to object) at address 0x73f5748e5c98

Most likely, you have hit a bug, but this error can also be caused by malfunctioning hardware.

BuildID[sha1]=f2c92ca4c390c2a53fc641dcd9d1cdb92fe79d3b

Thread pointer: 0x0

Attempting backtrace. You can use the following information to find out

where mysqld died. If you see no messages after this, something went

terribly wrong...

stack_bottom = 0 thread_stack 0x100000

 #0 0xc65db0 <unknown>

 #1 0x73f520e456ef <unknown>

 #2 0x9f457f <unknown>

 #3 0xa19471 <unknown>

 #4 0xa21e5e <unknown>

 #5 0x73f520e3058f <unknown>

 #6 0x73f520e3063f <unknown>

 #7 0x9eee74 <unknown>

 #8 0xffffffffffffffff <unknown>

The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains

information that should help you find out what is causing the crash
```

Docker Compose is the following:
```
  mysql:
    image: mysql:latest
    container_name: MySQL
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=<SOME_PASS>
    volumes:
      - $DOCKERDIR/mysql/db:/var/lib/mysql
```

Any help would be much appreciated.
