### ISSUE TITLE
Connection error "Host X is not allowed to connect to this MySQL server" when running two containers at the same time

### ISSUE THREAD

**Issue by ivokund** [docker-library/mysql#110]
Hi, I'm having trouble running two `mysql:5.7` containers simultaneously. 

I have two similar projects I'm running with `docker-compose`

`docker-compose.yml` for project "test1"
```yml
web:
    build: ./
    ports:
        - "81:80"
    expose:
        - "80"
    links:
        - db:database
db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: secret-root
        MYSQL_DATABASE: web
        MYSQL_USER: web
        MYSQL_PASSWORD: web
    entrypoint: /entrypoint.sh --innodb_buffer_pool_size=5M
```

`docker-compose.yml` for project "test" (all is same except the outer port)
```yml
web:
    build: ./
    ports:
        - "82:80"
    expose:
        - "80"
    links:
        - db:database
db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: secret-root
        MYSQL_DATABASE: web
        MYSQL_USER: web
        MYSQL_PASSWORD: web
    entrypoint: /entrypoint.sh --innodb_buffer_pool_size=5M
```

When I `docker-compose build` and `docker-compose up` these projects, I can see that all containers have started. Output from `docker ps`:

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                NAMES
fc3486b31d97        test2_web           "apache2-foreground"     27 minutes ago      Up 27 minutes       0.0.0.0:82->80/tcp   test2_web_1
3117ee56bf14        test1_web           "apache2-foreground"     28 minutes ago      Up 28 minutes       0.0.0.0:81->80/tcp   test1_web_1
8a44425b99ec        mysql:5.7           "/entrypoint.sh --inn"   38 minutes ago      Up 27 minutes       3306/tcp             test2_db_1
77bc6aedd17d        mysql:5.7           "/entrypoint.sh --inn"   About an hour ago   Up 28 minutes       3306/tcp             test1_db_1
```

Then I start a MySQL connection from `test_web_1` using the `DATABASE_PORT_3306_TCP_ADDR` environment variable.

So far so good. The problems start when I try to start a second connection from `test_web_2`. When trying to connect, I get an error `SQLSTATE[HY000] [1130] Host '172.17.2.52' is not allowed to connect to this MySQL server`. 

The DSN I use (from `DATABASE_PORT_3306_TCP_ADDR` env variable ) should be correct: `mysql:host=172.17.2.47;dbname=web` for test1 and `mysql:host=172.17.2.51;dbname=web` for test2. I use the default root username and password. 

The first container I start seems to always work (does not matter if it's test1 or test2). The second gives error 1130. It's the same when I try to connect from the host machine. For example

```
mysql -h 172.17.2.61 -P 3306 -u web -p
Enter password:
ERROR 1130 (HY000): Host '172.17.42.1' is not allowed to connect to this MySQL server
```
While connecting to the container that started first works. 

Running docker v1.8.1, docker-compose 1.5.0rc1. `/etc/mysql/my.cnf` is the same as in the mysql image, so `bind-address` is commented out. 

What could be the cause for this issue? Is this a known issue or am I doing something completely wrong? Thanks!
