### ISSUE TITLE
ERROR 1396 (HY000): Operation CREATE USER failed for 'root'@'%'

### ISSUE THREAD

**Issue by innovia** [docker-library/mysql#129]
we are struggling to figure this one out

it does not work out of the box - running on OSX

everytime we attempt to start it it fails after intializing the db but when we run it a 2nd time mysql runs becuas ethe DATA_DIR folder already exists

why does it keep failing?

running version 5.6.28 of mysql WITHOUT MODIFICATIONS!

also worth mentioning we see the issue only with docker-compose, 

seems like the root user is the one being used to log in to mysql and then attempt to create it while logged in as root fails

**Comment by yosifkit** [comment]
I assume this is the entrypoint script in the mysql image that is failing.

Is it the usual way to modify the `root` user in sql while being the `root` user and works fine without `docker-compose`.  What does your yaml have configured for the mysql container?

**Comment by Ninir** [comment]
@yosifkit I assume @innovia has this kind of configuration:

```yaml
db:
    image: mysql:5.7.10
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: mydb
        MYSQL_USER: root
        MYSQL_PASSWORD: root
    ports:
        - 3306:3306
```

It is also failing for me, but running `docker-compose up` again makes it.
