### ISSUE TITLE
database not initialized when run via docker-compose

### ISSUE THREAD

**Issue by cjrollo** [docker-library/mysql#171]
MySQL version: 5.7.12

I send this via command line and the "demo" database is created, as is the "demouser" user:

`docker run -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=demo -e MYSQL_USER=demouser -e MYSQL_PASSWORD=demopassword -d mysql:5.7.12`

When I run via docker-compose, the "demo" database is *not* created. Here is the relevant info from docker-compose.yml:

```yaml
db:
  image: mysql:5.7.12
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=demo
    - MYSQL_USER=demouser
    - MYSQL_PASSWORD=demopassword
  ports:
    - 3306:3306
```

I noticed that the shell process for docker run is "/entrypoint.sh mysql" but docker-composer runs "docker-entrypoint.sh". Why does docker-entrypoint.sh differ in behaviour?
