### ISSUE TITLE
Docker-compose  : how to initialize mysql database from remote host

### ISSUE THREAD

**Issue by nserebry** [docker-library/mysql#178]
Hi, _sorry if this is a duplicate_ but I tried to search for this answer and got no luck yet.
I'm creating a docker-compose.yml file (Currently, I'm dumping  *.sql schema from local)

I would like to create a`mysqldump` file  from remote db (_with just a database schema without actual data_)  and add it to mysql container during the docker-compose 'build' step.
Can you please point me how this  can be done ?
I probably can add something like     `- /mysql_data:/var/lib/mysql`  but how do I add remote db details(host, user, pass?) ?

``````
mysql:
    hostname: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: MyNewPass
      MYSQL_DATABASE: mydb
      MYSQL_USER: aurora
      MYSQL_PASSWORD: MyNewPass
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d:ro```

thank you 
``````
