### ISSUE TITLE
Docker Compose mysql MYSQL_ROOT_PASSWORD not work

### ISSUE THREAD

**Issue by iawia002** [docker-library/mysql#180]
here is my config file:
```yaml
mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=test
    - MYSQL_DATABASE=test
```
I start docker, when i try to connect mysql using `test` as password, failed.
the password is still `root`
