### ISSUE TITLE
Files in docker-entrypoint-initdb.d are ignored

### ISSUE THREAD

**Issue by marcelgwerder** [docker-library/mysql#189]
Not sure what I'm doing wrong or if this is a bug,  I always get:
```
...
/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
...
```
My config looks like:
```yml
services:
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    volumes:
      - ./db-data:/docker-entrypoint-initdb.d
      - ./db-conf:/etc/mysql/conf.d
```

And I have a `.sql` file in `./db-data`.
