### ISSUE TITLE
Docker-compose creates database with collation swedish

### ISSUE THREAD

**Issue by ptahchiev** [docker-library/mysql#201]
Hello,

in my docker-compose file I have the following:

````
  db:
     image: mysql
     command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
     container_name: nemesis-db
     environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=samplestore
      - MYSQL_USER=XXXX
      - MYSQL_PASSWORD=XXXX
````

When the container is started the `samplestore` database is created with `latin1_swedish_ci`.
I can login with ssh and  verify that. I can create a new table in the `samplestore` database and it is again created with the swedish collation. However, if I create a new database:
````
create database test;
````

and then a new table in the `test` database it is all ok and the collation is UTF-8. So I believe it has to do something with this file `/usr/local/bin/docker-entrypoint.sh`.
