### ISSUE TITLE
docker container exiting suddenly

### ISSUE THREAD

**Issue by pahakrai** [docker-library/mysql#204]
```
version: "2.0"
services:
  data:
    build: docker/.
    volumes:
       - ./docker/data:/docker-entrypoint-initdb.d
    command: "true"
  mysql:
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes_from:
      - data

```

The above docker compose is to test sql dump form /docker/data folder. But the problem occurs when I build up the docker-compose up -d for the first time the container suddenly exits. And after building the compose again it runs. The dump sql file is showing in the docker-entrypoint-initdb.d but sql dump is not working as I can see no database with mysql commands. I thought it might be a volume problem I have already tried docker-compose rm -vf but still not working. May be problem with the entrypoint.sh. I am lost here could anyone guide me with the problem here.
