### ISSUE TITLE
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)

### ISSUE THREAD

**Issue by aarongeiser** [docker-library/mysql#219]
Hello - 

I have been unable to get the MySQL container to initialize.  I consistently get the above error.  I have attempted to remove the .data folder and re-initialize the container.  No luck. 

The other two containers build and run fine.  I have had the MySQL container run successfully once or twice - but only after a complete system restart.  I have not been able to reproduce the successful running of the container - otherwise I wouldn't be posting this issue.  ;)

Docker version 1.12.1, build 6f9534c
docker-machine version 0.8.1, build 41b3b25

[docker-compose.yml]

```
version: '2'

services:
    mysql:
        image: mysql:5.7.15
        ports:
            - 3306:3306
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build: docker/php7-fpm
        ports:
            - 9000:9000
        links:
            - mysql:synthesizer
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs
    nginx:
        build: docker/nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
```

[docker logs]

```
mysql:5.7.15        "docker-entrypoint.sh"   14 seconds ago      Exited (1) 14 seconds ago

Initializing database
mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
2016-10-05T04:26:41.741277Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-10-05T04:26:41.749972Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
2016-10-05T04:26:41.750014Z 0 [ERROR] Aborting
```

**Comment by yosifkit** [comment]
Since you seem to be running on OSX or Windows, add in a `user: 1000:50`.  It defaults to running as the `mysql` user which is not able to access folders mounted from OSX/Windows.

**Comment by ikbenben** [comment]
@yosifkit I'm also experiencing this issue. Where would you specify the `user: 1000:50`. I assumed as a child of the mysql: image definition but htis is indicating it is invalid as it should be a string

    services:
      wp_db:
        user: 1000:50
        ...

This is the output I get when I try to bring it up:

    MacBook-Pro:wordpress-site brooney$ docker-compose up
    ERROR: The Compose file './docker-compose.yml' is invalid because: services.wp_db.user contains an invalid type, it should be a string

**Comment by yosifkit** [comment]
@ikbenben, It just needs some quotes around it `user: "1000:50"`.

**Comment by yosifkit** [comment]
This issue seems to be solved; feel free to comment if you feel it was closed in error.

**Comment by anuragde** [comment]
Hi, I'm facing a similar issue, below is my `docker-compose.yml`
```
version: '3.3'
services: 
  docker-mysql:
    image: mysql:latest
    volumes:
      - "./db-data:/var/lib/mysql"
    restart: always
    ports:
      - "3307:3306"
    user: "1000:50"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=root
  spring-boot-jpa-docker-webapp:
    image: springboot_docker
    depends_on:
      - docker-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=docker-mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=test  
      - DATABASE_PORT=3306
```
