### ISSUE TITLE
chown: changing ownership of '/var/lib/mysql/ibtmp1': No such file or directory

### ISSUE THREAD

**Issue by bdestrempes** [docker-library/mysql#233]
Hi,

Trying to start a container gives me this message:

`chown: changing ownership of '/var/lib/mysql/ibtmp1': No such file or directory`

The container was created with docker-compose:

```
version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     ports:
      - "8081:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
      - ./:/var/www/html
     links:
       - db
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress

   phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8090:80"
    links:
      - db:db
```

This worked perfectly for the first instance but trying to create a new instance in another directory gives the above error message.

I have searched around but couldn't find anything related to this error message. I am running Docker for Windows 1.12.3. Still new to this so apologies if this is something simple that I missed.
