### ISSUE TITLE
ER_HOST_NOT_PRIVILEGED: Host '172.19.0.3' is not allowed to connect to this MySQL server

### ISSUE THREAD

**Issue by UpCoder** [docker-library/mysql#235]
I write a docker-compose that contains a website and a mysql
in my docker-compost, ,there write as follow:
```
version: '2.0'
services:
    website: 
        build: 
            context: /Users/Liang/Desktop/dockercompose/website/
            dockerfile: ./Dockerfile
        ports: 
            - "3001:3001" 
        links:
            - website_mysql:website_mysql
        depends_on:
            - website_mysql
        container_name: "website"
    website_mysql:
        build: 
            context: /Users/Liang/Desktop/dockercompose/mysql/
            dockerfile: ./Dockerfile
        container_name: "website_mysql"
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD="xA123456"
```
when I exec docker-compose up
there is a error when execute "npm start" in my website container. the error is a title.
maybe it caused by the remote access authority, but i don't know how to fix it
please help me, thank you very much
