### ISSUE TITLE
Importing huge dump is freezing after 5-10%

### ISSUE THREAD

**Issue by utegental** [docker-library/mysql#240]
I'm trying to import huge dump file(~30Gb) and it's freezing.
Tested import via terminal command and via UI tools like MySQLWorkbench and SequelPro.
May be I need some kind special configuration?

Part from docker-compose:
```yaml
mysql:
    image: mysql:5.7
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    restart: always
```
[You can rename extension to .cnf and test it](https://github.com/docker-library/mysql/files/610520/my.txt)
