### ISSUE TITLE
Database not initializing (from sql dump) on "docker for windows" with mapped host directory for data directory

### ISSUE THREAD

**Issue by artur2000** [docker-library/mysql#264]
We use Docker for Windows on Windows 10 Pro and try to persist the database data in the host filesystem using a volume mapping for the mysql service container (using docker-compose).

Here is the corresponding docker compose config:

```
  # mysql server
  mysql:
    build: ../mysql/dev
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: project_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: masterpassword
    volumes:
      - d:/docker/mysql/var/lib:/var/lib/mysql

```

The host directory (d:/docker/mysql/var/lib) is created as expected and the default mysql databases (test, mysql, performance_schema) are created as well.

But the project database is not initialized during the first run (from a dump file).

There is no issue with this initialization on a linux host, so I assume docker-compose config file as well as the database dump integration in Dockerfile are correct.

For completness, here is the dockerfile for the mysql service.

```
FROM mysql:5.5

# prevent dpkg errors
ENV TERM=xterm-256color

RUN apt-get update && apt-get install -y \
    -o APT::Install-Recommend=false -o APT::Install-Suggests=false \
    net-tools \
    nano \
    bc

# initial project database
COPY project_app.sql.gz /docker-entrypoint-initdb.d/001_project.sql.gz
COPY mysql-tuning-primer.sh /usr/local/bin/

# custom mysql configuration
COPY project.cnf /etc/mysql/conf.d

RUN chmod a+x /usr/local/bin/mysql-tuning-primer.sh \
    && chmod 644 /etc/mysql/conf.d/project.cnf
```

**Comment by yosifkit** [comment]
What does your Dockerfile look like?  I assume it contains something like `COPY dump.sql /docker-entrypoint-initdb.d/`?  Is `d:/docker/mysql/var/lib/` empty when you first start?  The initdb.d files are only used on first initialization, so they won't be run if the database was already initialized on a previous run.  Did you share the `d:` drive with "Docker for Windows"?

**Comment by Marchys** [comment]
Same issue in Windows 10, I've tried building the image and in the docker compose:

```
version: '2.1'
services: 
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tripleLoop
    volumes:
      - /Users/barro/Documents/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
```
Tried deleting all the volumes, images and containers and in the container the init.sql is present in the docker-entrypoint-initdb.d folder. After all that it seems that the init.sql is not executed. What I'm missing? (the only mysql image that works for me is the 8.0)
