### ISSUE TITLE
User not created when using secrets in kubernetes

### ISSUE THREAD

**Issue by hoeghh** [docker-library/mysql#270]
Hi,

I have a Kubernetes 1.5 cluster running, where i want to run MySQL. The password for Root i put in a secret. This is then injected as an env variable and i can confirm that it is 

```
root@mysql-0:/# env |grep MYSQL                                                                                                                                                
MYSQL_VERSION=5.6.35-1debian8
MYSQL_PASSWORD=jirapassword
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_PORT_3306_TCP=tcp://10.32.0.245:3306
MYSQL_MAJOR=5.6
MYSQL_PORT_3306_TCP_PROTO=tcp
MYSQL_PORT_3306_TCP_ADDR=10.32.0.245
MYSQL_SERVICE_PORT=3306
MYSQL_USER=jira
MYSQL_ROOT_PASSWORD=rootpassword
MYSQL_PORT=tcp://10.32.0.245:3306
MYSQL_SERVICE_HOST=10.32.0.245
```

When i try to connect to mysql, it fails:
```
root@mysql-0:/# mysql -h localhost -u root -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```

Heres my statefulset yaml:
```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        volumeMounts:
        - name: database
          mountPath: /var/lib/mysql
        - name: config-volume
          mountPath: /etc/mysql
      volumes:
      - name: database
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: config-volume
        configMap:
          name: mysql-config
```

And here my secret (base64):
```
apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: cm9vdHBhc3N3b3JkCg==
  mysql-user: amlyYQo=
  mysql-password: amlyYXBhc3N3b3JkCg==
```

As you can see, i can login if i specify the env variables directly in the deployment/statefulset yaml : 
```
root@mysql-0:/# mysql -h localhost -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 5
Server version: 5.6.35 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```
I dont know why this is. If i made an misstake, please let me know, otherwise if its an error in the image, it makes mysql more or less useless when run in Kubernetes. I dont know the timing for when secrets are put into pods/containers, but something is not right.

I have a cluster running on my laptop, if anyone wants me to test things.
