### ISSUE TITLE
Init .sql, .sh, .sql.gz are not executed if a volume is mounted?

### ISSUE THREAD

**Issue by lucile-sticky** [docker-library/mysql#277]
Hello there!

## Theme:
I've spotted a difference between the behavior of MySQL container creation if there is a volume or not containing a database mounted in it. I don't know if it's wanted, that's why I ask here.

### Custom docker-compose.yml:
```yaml
version: '2'

services:
  web:
    build: ../custom-web/
    ports:
     - "80:80"
    tty: true
    depends_on:
     - custom-mysql
    links:
     - custom-mysql:custom-mysql

  custom-mysql:
    build: ../custom-mysql/
    ports:
     - "3306:3306"
#    volumes:
#     - /var/lib/mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=root_pwd
     - MYSQL_DATABASE=database
     - MYSQL_USER=test
     - MYSQL_PASSWORD=test_pwd
```

### Custom MySQL Dockerfile:
```bash
FROM mysql:5.7

# Add SQL file to run it on the container creation
ADD default.sql /docker-entrypoint-initdb.d/default.sql
```

### Default sql file:
```sql
SELECT 'I have been run!' AS '';
```

## Behavior:
- If there is no volume mounted (`volumes` lines commented in the `docker-compose.yml` file), the SQL file `default.sql` is run. 
- If the volume is mounted (`volumes` lines uncommented in the `docker-compose.yml` file) and there is a database in it, the SQL file `default.sql` is not run.

## Question:
Is that wanted? Because in the [Docker Hub documentation](https://hub.docker.com/_/mysql/), it's not clear that files stored in `/docker-entrypoint-initdb.d` will be run only if there is no database mounted with Docker volumes :confused: 
> #### Initializing a fresh instance
> 
> When a container is started for the first time, a new database with the specified name will be created and initialized with the provided configuration variables. Furthermore, it will execute files with extensions `.sh`, `.sql` and `.sql.gz` that are found in `/docker-entrypoint-initdb.d`. Files will be executed in alphabetical order. You can easily populate your mysql services by [mounting a SQL dump into that directory](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-file-as-a-data-volume) and provide [custom images](https://docs.docker.com/reference/builder/) with contributed data. SQL files will be imported by default to the database specified by the MYSQL_DATABASE variable.
