### ISSUE TITLE
docker Access denied for user in another container

### ISSUE THREAD

**Issue by tzookb** [docker-library/mysql#293]
I have a docker-compose file 
with several containers but I need help with 
- php 
- mysql

so I am able to connect from my host to the mysql container,
but when my php container tries to connect it gets "Access denied"

my compose file:

```

php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../../:/var/www/html
    networks:
      - appnet
    tty: true


mysqlDB:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "dbname"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "pass"
    volumes:
      - mysqltest:/var/lib/mysql
```

** its a clean slate, I removed volumes to make sure no old passwords are there.

**Comment by yosifkit** [comment]
I assume that your php is configured to use the same database/user/password?  Is the mysqlDB container also in the `appnet` network or some other network that php is in?  Otherwise, the php container shouldn't be able to connect to the database by the hostname of `mysqlDB`.  Not sure what your "networks" section looks like, but something like this should work:

```
version: '2'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../../:/var/www/html
    networks:
      - appnet
      - backend
    tty: true

  mysqlDB:
    image: mysql:5.7
# shouldn't need to expose ports unless you are connecting from your host
    environment:
      MYSQL_ROOT_PASSWORD: "pass"
      MYSQL_DATABASE: "dbname"
      MYSQL_USER: "username"
      MYSQL_PASSWORD: "pass"
    volumes:
      - mysqltest:/var/lib/mysql
    networks:
      - backend
```

I don't think this is the problem, since you are getting "Access denied" rather than "no route to host". :confused:
