### ISSUE TITLE
docker logs mbind: Operation not permitted

### ISSUE THREAD

**Issue by coding-chenkaikai** [docker-library/mysql#303]
你好，执行docker run mysql:8.0.1的时候，docker logs 查看容器日志出现mbind: Operation not permitted，最初以为是权限的问题，添加--cap-add=ALL参数，还是会出现该日志，请问下该问题的影响范围是什么以及如何避免出现？

**Comment by D1W0U** [comment]
same issue here

**Comment by ltangvald** [comment]
The server use mbind for NUMA (non-uniform memory access) operations, but Docker blocks this access by default. It's possible to provide a custom profile that allows it, but the syntax of the profile files has changed across Docker versions, so it's kind of messy. There's more about this here: https://docs.docker.com/engine/security/seccomp/

**Comment by tianon** [comment]
Closing since this is more an issue with the default configuration of Docker's seccomp profile, and there's not anything we can do to fix this in the image itself.

See https://github.com/docker-library/mongo/issues/113 for a similar issue over on the `mongo` image.

As noted there, adding something to the documentation (especially referencing the error message) would be a great idea. :+1:

**Comment by johncmunson** [comment]
All of a sudden I started getting these mbind errors as well. For me, the solution was locking down the version of the mysql docker image. I changed my `docker-compose.yml` from...
```
services:
  mysqldb:
    image: mysql
```
to...
```
services:
  mysqldb:
    image: mysql:5.7.22
```

**Comment by nirodg** [comment]
None of this issues does work for me. I've tried on my local env, on a virtual machine and even on a VPS and nothing, same issue.  I've tried using a different version and it crashes, seriously thinking it might be a bug or something.
```yml
version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql.dev
    restart: always
    ports:
     - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: brage
      MYSQL_DATABASE: mysqlapp

  adminer:
    image: adminer
    restart: always
    links:
      - mysql
    ports:
      - 18080:8080
```

The only way to connect is by ``docker exec -it mysql.dev mysql -u root -p``
