### ISSUE TITLE
Error creating root user

### ISSUE THREAD

**Issue by lupa18** [docker-library/mysql#307]
This is the error: 
`[Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.`

and my docker-compose file says: 
```
db:
  image: mysql:latest
  restart: unless-stopped
  environment:
    MYSQL_ROOT_PASSWORD: mypassword
  volumes:
    - db:/var/lib/mysql
```
