### ISSUE TITLE
Set SSL with docker-compose

### ISSUE THREAD

**Issue by silverfangs** [docker-library/mysql#314]
Hi guys,

Wanted to ask is anyone know how to set the SSL with docker-compose?
Thanks in advance!

**Comment by yosifkit** [comment]
It should be already working.  The images [automatically create](https://github.com/docker-library/mysql/blob/e207dbbdfd5c95e4b51bdc2dae62c5f72a1dd908/5.7/docker-entrypoint.sh#L94-L99) self signed certs using `mysql_ssl_rsa_setup`.

**Comment by silverfangs** [comment]
Hi,
Somehow in my local MySQL Workbench I still manage to login to the DB even though I have set 
`GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' REQUIRE SSL WITH GRANT OPTION;`.

I spin up the docker DB using docker-compose with `yml` setting as:
```yml
version: '2'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - ./my/custom:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: root
```

Any idea about this? I believe I have missing something here...
