### ISSUE TITLE
I use java in docker,when I connect the mysql:8.0 in docker .It cannot connect.But when I change mysql to latest，It succees.

### ISSUE THREAD

**Issue by 9526xu** [docker-library/mysql#316]
This is my config in docker.

### java
```
sion-web:
  build: /home/docker_project/sion/sion
  volumes:
    - /home/.m2:/root/.m2
    - /home/docker_project/logs:/home/admin/app/logs
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "8082:8082"
  restart: always
  external_links:
    - mysql
```

### mysql 
```
mysql:
  image: mysql:8.0
  ports:
    - "3306:3306"
  volumes:
    - /home/docker_project/mysql:/var/lib/mysql
    - /etc/localtime:/etc/localtime:ro
  environment:
    MYSQL_ROOT_PASSWORD: qwer123
  container_name: mysql

```
