### ISSUE TITLE
Allow to specify the initdb folder using env variable

### ISSUE THREAD

**Issue by AndreaGiardini** [docker-library/mysql#325]
Instead of hardcoding `/docker-entrypoint-initdb.d/*` in the init script it would be nice to make it scriptable using env variables.

In my case I would like to mount a secret sql file that creates all the users, so it would be nice to have something like: `INIT_SQL_SCRIPT: /run/secrets/mysql_init_sql`

**Comment by yosifkit** [comment]
You could just throw a symlink in the `/docker-entrypoint-initdb.d/` to point to `/run/secrets/mysql_init_sql`.  Something like this?

```Dockerfile
FROM mysql:5.7
RUN ln -sf  /run/secrets/mysql_init_sql /docker-entrypoint-initdb.d/my.sql
```

Also, in newer versions of Docker (17.06+) you can specify the secret`s path and skip the symlink altogether.

**Comment by AndreaGiardini** [comment]
Yeah i'm aware of this solution, my suggestion was to implement it in the official image, this would avoid to rebuild the image.

I can imagine that one of the most common use case for `docker-entrypoint-initdb.d` is creating users and granting access. So why not doing it directly in the official image instead of having everybody build their own sub-image?

Also, I can't find any reference about mounting secrets in a specific path. Can you point me to the correct documentation? I am using docker-compose ( https://docs.docker.com/compose/compose-file/#secrets )

**Comment by yosifkit** [comment]
I'm not 100% certain if docker-compose will work with a full path, but it is mentioned with an example in the [Docker Secrets document](https://docs.docker.com/engine/swarm/secrets/#how-docker-manages-secrets).

> In Docker 17.05 and earlier, secrets are always located within the /run/secrets/ directory. Docker 17.06 and higher allow you to specify a custom location for a secret within the container. The two examples below illustrate the difference. The older version of this command requires you to create a symbolic link to the true location of the site.conf file so that Nginx can read it, but the newer version does not require this. The older example is preserved so that you can see the difference.
>
> - Docker 17.06 and higher:
>
>```console
> $ docker service create \
>     --name nginx \
>     --secret site.key \
>     --secret site.crt \
>     --secret source=site.conf,target=/etc/nginx/conf.d/site.conf \
>     --publish 3000:443 \
>     nginx:latest \
>     sh -c "exec nginx -g 'daemon off;'"
>```

**Comment by AndreaGiardini** [comment]
I tried this:

```
  db:
    #build: ./build/mysql/8.0
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: '/run/secrets/mysql_root_password'
    security_opt:
      - seccomp:unconfined
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - source: mysql_root_password
      - source: mysql_init_sql
        target: /docker-entrypoint-initdb.d/init.sql
```

but still...

```
root@srv:~# docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:58:57 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@srv:~# docker exec -it db bash
root@cont:/# ls /docker-entrypoint-initdb.d/
root@cont:/# ls /run/secrets/docker-entrypoint-initdb.d/init.sql 
/run/secrets/docker-entrypoint-initdb.d/init.sql
```

maybe docker-compose does not support it?
