### ISSUE TITLE
MySQL 5.6 quits

### ISSUE THREAD

**Issue by jbehrens94** [docker-library/mysql#333]
I am using `Docker version 17.09.0-ce, build afdb6d4` on macOS 10.13 High Sierra. `docker info` below:

```Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: LZH5:NLQ6:T5U6:SLLB:DTQV:PJDO:KE26:LATC:6TKI:AJ73:NLIQ:X46M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 49
 Goroutines: 61
 System Time: 2017-10-15T19:22:52.860161811Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I'm using the following MySQL setup in my `docker-compose.yml`:

```
version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"

  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80

  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - 33061:3306
volumes:
  dbdata:
```

This is what happens when I run `docker-compose up`:

```
database_1  | 2017-10-15 19:22:18 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
database_1  | 2017-10-15 19:22:18 0 [Note] mysqld (mysqld 5.6.37) starting as process 1 ...
nultienapi_database_1 exited with code 1
```
