### ISSUE TITLE
Port binding expose always 3306

### ISSUE THREAD

**Issue by adrianofoschi** [docker-library/mysql#344]
Hello, I'm running a mysql container. The internal container port is normally 3306, I should want to map this port to 8082 on host. I'm using docker-compose:

```
    mysql:
      image: mysql:5.7
      container_name: 4hse-www-mysql
      working_dir: /application
      volumes:
        - ../:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=4hse
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "8083:3306"
      expose:
        - "8083"
      command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
      networks:
        hse_www_net:
          ipv4_address: 172.25.0.4
```

The problem is that it doesn't connect on 172.25.0.4:8083 but it works on 172.25.0.4:3306.
Why?
