### ISSUE TITLE
No support for windows/amd64

### ISSUE THREAD

**Issue by tmszyman** [docker-library/mysql#346]
docker-compose.yml

```
version: '3.1'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
```

`docker-compose up`

> Pulling db (mysql:5.7)...
> 5.7: Pulling from library/mysql
> ERROR: no matching manifest for windows/amd64 in the manifest list entries
