### ISSUE TITLE
Segmentation fault when using MySQL with volume on macOS

### ISSUE THREAD

**Issue by miks** [docker-library/mysql#372]
macOS version: 10.13.3
Filesystem: APFS
Docker version: 17.12.0-ce

When starting docker-compose first time with no volumes prior existing, mysql initialization always ends with:
`/usr/local/bin/docker-entrypoint.sh: line 201:    61 Segmentation fault      mysql_ssl_rsa_setup --datadir="$DATADIR"`
therefore no mysql root password or any other customization from docker-entrypoint.sh is set.

When no volumes is defined within compose file, mysql initialization ends correctly.
No errors with same compose file on Ubuntu 16.04.

example docker-compose.yml
```
version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
          - mysql:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: somepassword

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql:
```
