### ISSUE TITLE
Can't get rights after restore dump on 8.0.4 (with mysql database from 8.0.2) and restart container.

### ISSUE THREAD

**Issue by bscheshirwork** [docker-library/mysql#388]
I have 2 time reach this situation: 
user rightsless after some days.
Like to #380
First time I try to remove all mysql data from engine folder and `docker-compose up` again.
(with restore dumps of course)
but this is happens again

```
SQLSTATE[HY000]: General error: 1356 View 'information_schema.COLUMNS' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
The SQL being executed was: SHOW FULL COLUMNS FROM `user`

Error Info: Array
(
    [0] => HY000
    [1] => 1356
    [2] => View 'information_schema.COLUMNS' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
)
```

I try to connect from running container
```sh
docker-compose exec mysql bash
mysql -uroot -p
mysql> show databases;
ERROR 1449 (HY000): The user specified as a definer ('mysql.infoschema'@'localhost') does not exist
mysql> show create user root;
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE USER for root@%                                                                                                                                                                                             |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| CREATE USER 'root'@'%' IDENTIFIED WITH 'mysql_native_password' AS '*48916CC66536B997B4401FD7C606CCF364ED2C16' REQUIRE NONE PASSWORD EXPIRE DEFAULT ACCOUNT UNLOCK PASSWORD HISTORY 0 PASSWORD REUSE INTERVAL 0 DAY |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show tables from targetbd;
ERROR 1449 (HY000): The user specified as a definer ('mysql.infoschema'@'localhost') does not exist
mysql> 
```
this is like to #380 too

**Comment by tianon** [comment]
MySQL 8.0 is still a preview release -- I'd recommend sticking to 5.7 for
now if you need a stable base.

On your issue -- does your application do anything to modify the database?
Have you pulled the latest version of the image?  Are you trying to upgrade
directly from 5.7 to 8.0 without doing the appropriate upgrade steps?

**Comment by bscheshirwork** [comment]
> Have you pulled the latest version of the image? Are you trying to upgrade directly from 5.7 to 8.0 without doing the appropriate upgrade steps?

1. `docker-compose.yml` have service `mysql` some like this
```yml
  mysql:
    image: mysql:8.0.4
    ports:
      - "3308:3306" #for external connection
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password'] # https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_default_authentication_plugin
    # docker exec -ti projects_mysql_1 bash
    volumes:
      - ../mysql-data-test/db:/var/lib/mysql #mysql-data
    environment:
      TZ: Europe/Moscow
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: yiitest
      MYSQL_USER: travis
      MYSQL_PASSWORD: travis
```
2. remove all previous data from `/mysql-data-test`
3. up -d
4. restore dump
