### ISSUE TITLE
Initalizing from a not empty volume throws error

### ISSUE THREAD

**Issue by jaschaio** [docker-library/mysql#398]
I get the Following error:

`--initialize specified but the data directory has files in it. Aborting.`

Which is kind of expected as the volume I am mounting is not empty, but initalizing from a previous database. I created the directory by inspecting a previous mysql container with `docker inspect` as explained [here](https://dev.mysql.com/doc/refman/5.7/en/docker-mysql-more-topics.html#docker-persisting-data-configuration) and than copying the directory specified under "Mounts" to the place where I am now mounting the new volume from.

Maybe that's wrong and that's why I am getting problems.

docker-compose.yml:
```
mysql:
        image: mysql/mysql-server:8.0
        container_name: mysql
        restart: always
        volumes:
            - ./mysql/conf/my.cnf:/etc/my.cnf
            - ./mysql/data:/var/lib/mysql
```

These seem to be related but non of the fixes worked for me: #290 #361 #365 #69

**Comment by qedrakmar** [comment]
I can't recreate this, but it's possible it might be in how you're copying.  Can you show the command you're using to copy the volumes around?  Can you also give us an ```ls -alh``` on that ./mysql/data directory?

**For reference:** 
I created a database and tables inside a mysql-server instance stood up with the following docker-compose.yml

```
version: '2'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
```

I then copied that folder both with ```sudo cp -R mysql mysql2``` and ```sudo rsync -avP mysql/* mysql3``` (trying both to see if it was a weird attribute flag issue).  I created 2 more services within the docker-compose.yml pointing to each of the copied directories and I was able to see my DB and table in both of them.  Just to verify, though, I did I lose some of the files when I tried copying or rsyncing without sudo.  The only other major differences are I don't have a my.cnf to specify, and I DO specify the ```MYSQL_ROOT_PASSWORD```, though that gets ignored if /var/lib/mysql is already populated.
