### ISSUE TITLE
Error MySQL:: read error database name upper case...

### ISSUE THREAD

**Issue by c3stream** [docker-library/mysql#399]
https://github.com/docker/for-mac/issues/2740

MySQL > DB mysql
Table: innodb_index_stats
Table: innodb_table_stats

rows DB name lower_case.... changed...Oh..

```
 mysql:
    restart: always
    image: mysql:5.6
    container_name: xxx-mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
```

Is OK! (Docker Community Edition 17.12.0-ce-mac55 2018-02-27)
A strange thing is happening, but I hope it will be solved.
