### ISSUE TITLE
Cannot connect mysql with another container

### ISSUE THREAD

**Issue by Rukeith** [docker-library/mysql#421]
I use docker compose to start mysql and nodejs server.
When container start my nodejs server will to run raw query to mysql, but I always got the access denied. Even I grant the permission or use root

![2018-05-03 17 20 47](https://user-images.githubusercontent.com/7069605/39609567-845db2e2-4f7c-11e8-9fe5-b7bead486792.png)

**Comment by wglambert** [comment]
Could you post the docker-compose.yml

**Comment by Rukeith** [comment]
@wglambert Here is my docker-compose.yml

```
version: "3.6"
services:
  mysql:
    build:
      context: ..
      dockerfile: docker/Dockerfile-mysql
    image: bizcloud_mysql:ci-label
    container_name: biz-mysql-ci-label
    labels:
      - "CI-TEST=ci-label"
    networks:
      - ci-network
    ports:
      - "3306:3306"

  license:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: bizcloud_license:ci-label
    container_name: biz-license-ci-label
    labels:
      - "CI-TEST=ci-label"
    networks:
      - ci-network
    ports:
      - "9502:9502"
    depends_on:
      - mysql
    privileged: true

networks:
  ci-network:
    labels:
      - "CI-TEST=ci-label"
    name: ci-network
```
