### ISSUE TITLE
Can't restart an instance on macOS

### ISSUE THREAD

**Issue by atrauzzi** [docker-library/mysql#433]
It seems like I can start fresh containers and work with them normally.  But if anything causes the container to be stopped (host restart, etc), it's never able to come back up.

I get this error when I try to restart an instance:

```
mysql      | 2018-05-22T12:10:54.307467Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.columns_priv' doesn't exist
mysql      | 2018-05-22T12:10:54.307494Z 0 [ERROR] Fatal: can't initialize grant subsystem - 'Table 'mysql.columns_priv' doesn't exist'
mysql      | 2018-05-22T12:10:54.307688Z 0 [ERROR] Aborting
```

I've been working around this by dropping the container instance and then recreating and re-loading + re-migrating my database, but this is obviously a pain.

Here's my docker-compose for my usage of the image:

```
mysql:

    image: mysql:5
    container_name: mysql

    ports:
      - "3306:3306"

    volumes:
      - "/var/lib/mysql"
```

Is there anything that can be done to make life easier here?
