### ISSUE TITLE
Access denied for user 'user'@'%' to database 'database'

### ISSUE THREAD

**Issue by BentCoder** [docker-library/mysql#436]
MySQL user `user` (not the `root` one) cannot create a new database `hello` but can interact with existing databases if there is any. Is there any reason why `user` cannot create a new database? I want `user` to be able to create databases, tables so on. Just like `root`.

```
Couldn't create database.
MySQL said: Access denied for user 'user'@'%' to database 'hello'
```

I can login with `$ mysql -u user -ppassword` but still get the error below.

```
mysql> CREATE DATABASE hello;
ERROR 1044 (42000): Access denied for user 'user'@'%' to database 'hello'
```

**CONTAINER**
```
$ docker exec -it app_mysql_1 bash
mysql@b34d47faabb9:/$ mysql -u root -proot
Server version: 5.7.22 MySQL Community Server (GPL)

mysql> USE mysql;

mysql> SELECT user, host FROM user;
+---------------+-----------+
| user          | host      |
+---------------+-----------+
| root          | %         |
| user          | %         |
| mysql.session | localhost |
| mysql.sys     | localhost |
| root          | localhost |
+---------------+-----------+
5 rows in set (0.00 sec)
```

**docker-compose.yml**

```
version: '3'

services:

    mysql:
        image: mysql:5.7.22
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        ...

    nginx:
        ...
```

**.env**
```
MYSQL_ROOT_PASSWORD=root
MYSQL_USER=user
MYSQL_PASSWORD=password
```
