### ISSUE TITLE
Would there be support to run mysql container with native authentication method?

### ISSUE THREAD

**Issue by Anand-Moghe** [docker-library/mysql#440]
Can something like this be supported on a docker-compose file in future ?

```
database:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
      - "default-auth=mysql_native_password"
```

**Because right now I am not sure how to use mysql container (tried 5.6, 5.7 tag but they are crashing).**
