### ISSUE TITLE
Getting ERROR 29 (HY000) - No such file or directory when trying to mount an existing db

### ISSUE THREAD

**Issue by flurin-telepathy-ai** [docker-library/mysql#487]
I run into the following problem when I try to mount an existing data directory. 

This is my compose file: 
```
version: "3.7"
services:
  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mydata/mysql:/var/lib/mysql
```
I copy the data into  `/mydata/mysql`

 by running 
`sudo rsync -avP /var/lib/mysql/* ./mydata/mysql`

When run the mysql cli inside the container and try to access mysql.user I get the following error. 
`ERROR 29 (HY000): File './mysql/user.MYD' not found (Errcode: 2 - No such file or directory)`

However, the file seems to be located under 
`/var/lib/mysql/mysql/user.MYD`

I can access previously created databases and the data seems to be there, but I cannot create new database users of course. 

I run Windows 10 with WSL. 

Happy to provide more info.

**Comment by flurin-telepathy-ai** [comment]
I think this has something to do with either docker for windows or wsl. It seems to work fine on a machine running on ubuntu.

**Comment by mabdelfattah** [comment]
I have the same problem!

**Comment by flurin-telepathy-ai** [comment]
> I have the same problem!
Try with a docker volume instead of a mount from your local filesystem
    volumes:
      - my_docker_volume:/var/lib/mysql

also, check firewall settings

**Comment by mabdelfattah** [comment]
The firewall settings are fine because I can see the files inside the docker containers, and I can edit some of them, only *.MYI and *.MYD files are corrupt.

**Comment by mabdelfattah** [comment]
@flurin-telepathy-ai 
it works with docker volumes (without mounting)

```
mysql:
  volumes:
    - my_docker_voluem:/var/lib/mysql

volumes:
  my_docker_volume: #no driver, not type, etc.
```

Any idea how can I take backup of this docker-volume in case I want to use it on a different machine later? Also, do you know if I can specify the volume path?
