### ISSUE TITLE
[ERROR] unknown variable 'default-character-set=utf8mb4'

### ISSUE THREAD

**Issue by SystemOutPrint** [docker-library/mysql#514]
throw exception when docker compose startup.

docker-compose version: 3.2
docker version:  18.06.1-ce

docker-compose.yaml
```
version: "3.2"
services:
  db:
    image: caijiahe/mysql
    build:
      context: ../mysql/mysql-image/
      cache_from:
        - mysql:5.7
    command: ["--character-set-server=utf8mb4",  "--collation-server=utf8mb4_unicode_ci", "--default-character-set=utf8mb4"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "hdhdhdhdhdhd"
      MYSQL_DATABASE: "hello"
      MYSQL_USER: "aaa"
      MYSQL_PASSWORD: "bbb"
```
Dockerfile
```
FROM mysql:5.7
  
COPY tables/ /docker-entrypoint-initdb.d/
```

**Comment by wglambert** [comment]
This is what I got without the `--default-character-set=utf8mb4`

```yml
version: '3.2'

services:

  db:
    image: mysql:5.7
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
```console
mysql> SELECT * FROM information_schema.SCHEMATA;
+--------------+--------------------+----------------------------+------------------------+----------+
| CATALOG_NAME | SCHEMA_NAME        | DEFAULT_CHARACTER_SET_NAME | DEFAULT_COLLATION_NAME | SQL_PATH |
+--------------+--------------------+----------------------------+------------------------+----------+
| def          | information_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | mysql              | utf8mb4                    | utf8mb4_unicode_ci     | NULL     |
| def          | performance_schema | utf8                       | utf8_general_ci        | NULL     |
| def          | sys                | utf8                       | utf8_general_ci        | NULL     |
+--------------+--------------------+----------------------------+------------------------+----------+
4 rows in set (0.01 sec)
```

If I try to add the `--default-character-set=utf8mb4`
```console
$ docker-compose logs -f
Attaching to mysql-514_db_1
db_1  | 
db_1  | ERROR: mysqld failed while attempting to check config
db_1  | command was: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-character-set=utf8mb4 --verbose --help"
db_1  | 
db_1  | 2018-11-12T18:51:34.917503Z 0 [ERROR] unknown variable 'default-character-set=utf8mb4'
db_1  | 2018-11-12T18:51:34.921247Z 0 [ERROR] Aborting
```
