### ISSUE TITLE
Connection timeout with nodejs app occasionally

### ISSUE THREAD

**Issue by Globegitter** [docker-library/mysql#52]
I am using docker-compose to connect a nodejs app to a mysql database with the following `.yml` file:
```yml
db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=sane
server:
  image: artificial/docker-sails:iojs-full-stable-pm2
  command: sails lift --verbose
  volumes:
    - server/:/server
  ports:
    - "1337:1337"
  links:
    - db
```

Often it works, but often I get a timeout and a warning `'2015-03-04 14:40:37 1 [Warning] IP address '172.17.0.15' could not be resolved: Temporary failure in name resolution'` I am not entirely sure if the issue is here, or in the app itself, since if I switch to the postgresql I have no issues as well.

Still trying to nail down where exactly the issue arises, this is more to keep track of it in case it is an issue with the image being slow or something.

**Comment by RobLoach** [comment]
Looks like you're trying to link the `db` to the same host. `links` should point to other container you want to connect to:
https://docs.docker.com/compose/yml/#links

**Comment by Globegitter** [comment]
@RobLoach Sorry could you clarify? Does that not link `db` to `server`? The connection does work occasionally and then it saves everything properly to the db, etc.

**Comment by RobLoach** [comment]
Specify `links` for connections that you want to make from one container to the other. Seems strange to specify a link from one container to itself.

**Comment by Globegitter** [comment]
In the example above it states:

```yml
server:
  links:
    - db   
```

As far as I can see that is exactly what you say - from one container to another. I think compose might even throw an error if you link a container to itself.
