### ISSUE TITLE
centos7.5, mysql8.0.13 can't  init because Permission denied

### ISSUE THREAD

**Issue by haytoo1** [docker-library/mysql#523]
can anyone help me

this is error message:  
```
[root@VM_180_240_centos php_development_environment]# dc up mysql8
Recreating php_development_environment_mysql8_1_407378c4cc14 ... done
Attaching to php_development_environment_mysql8_1_407378c4cc14
mysql8_1_407378c4cc14 | Initializing database
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.394709Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not usingthis option as it' is deprecated and will be removed in a future release.
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.394896Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.13) initializing of server in progress as process 27
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.399475Z 0 [ERROR] [MY-010187] [Server] Could not open file '/var/log/mysqld.error.log' for error logging: Permission denied
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.399513Z 0 [ERROR] [MY-013236] [Server] Newly created data directory /var/lib/mysql/ is unusable. You can safely remove it.
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.399522Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql8_1_407378c4cc14 | 2018-12-06T08:04:37.399859Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.13)  MySQL Community Server - GPL.
```

this is Dockerfile:
```
FROM mysql:8.0.13
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai
```

this is docker-compose.yml:
```
    mysql8:
        restart: always
        build:
            context: $PWD/mysql8/build
            dockerfile: Dockerfile
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - $PWD/mysql8/data:/var/lib/mysql:rw
            - $PWD/mysql8/myd.cnf:/etc/mysql/conf.d/myd.cnf:rw
            - $PWD/mysql8/logs/:/var/log/:rw
        environment:
            - MYSQL_ROOT_PASSWORD=12345678@aA
            - TZ=Asia/Shanghai
        command: --default-authentication-plugin=mysql_native_password
        cap_add:
            - ALL
        privileged: true
```

this is other info:
```
// selinux
[root@VM_180_240_centos php_development_environment]# getenforce
Disabled

// kernel
[root@VM_180_240_centos php_development_environment]# uname -a
Linux VM_180_240_centos 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

// centos version
[root@VM_180_240_centos php_development_environment]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
```
