### ISSUE TITLE
Container in shared network cannot remotely connect to mysql

### ISSUE THREAD

**Issue by UserProgrammer** [docker-library/mysql#532]
I noticed that I can't remotely connect to a mysql server with the following docker-compose.yml file:
```
version: '3'

services:
  server:
    image: mysql:latest
    container_name: server
    environment:
    - MYSQL_ROOT_HOST=client
    - MYSQL_ROOT_PASSWORD=rootpass

  client:
    image: mysql:latest
    container_name: client
    environment:
    - MYSQL_ROOT_PASSWORD=client_root_pass
```
I go into the client container
`docker exec -it client /bin/bash/`
attempt to connect to the the server
`mysql -h server -root -prootpass`
and get the following error message
`ERROR 1130 (HY000): Host '172.22.0.3' is not allowed to connect to this MySQL server`

However, if I go into the server container and create a new root user
```
docker exec -it server /bin/bash/
mysql -prootpass
CREATE USER 'root'@'172.22.0.3' IDENTIFIED BY 'newpass';
```
return to the client
`docker exec -it client /bin/bash/`
and connect to the mysql server
`mysql -h server -u root -pnewpass`
it works.

I'm aware that setting MYSQL_ROOT_HOST=% would work, but I want to limit the connection to just the client container. Is there a way to accomplish this without having to manually create a user with the container's IP address?
