### ISSUE TITLE
MySQL 8 docker-compose :Failed to access directory for --secure-file-priv 

### ISSUE THREAD

**Issue by sharonsahadevan** [docker-library/mysql#541]
Hi,

when I started the container using docker-compose up, I am getting below error.
```logs
_**_Attaching to mysql
mysql    | 
mysql    | ERROR: mysqld failed while attempting to check config
mysql    | command was: "mysqld --verbose --help"
mysql    | 
mysql    | mysqld: Error on realpath() on '/var/lib/mysql-files' (Error 2 - No such file or directory)
mysql    | 2019-02-13T17:30:55.780793Z 0 [ERROR] [MY-010095] [Server] Failed to access directory for --secure-file-priv. Please make sure that directory exists and is accessible by MySQL Server. Supplied value : /var/lib/mysql-files
mysql    | 2019-02-13T17:30:55.786696Z 0 [ERROR] [MY-010119] [Server] Aborting_**_
```

my object is mapping my.cnf file to host directory so I can able to do the changes easily and changes will be persisted. I used official mysql image.

please guide me on how to solve this issue using docker-compose method.

docker compose file:
===============
```yml
version: '3.3'
services:
  mysql:
    container_name: mysql
    image: 'mysql:8'
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /var/data/mysql:/var/lib/mysql
      - /etc/mysql:/etc/mysql

    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: cdr
      MYSQL_PASSWORD: secret123
```

**Comment by wglambert** [comment]
Looks like a configuration error with the files you're mounting to `/etc/mysql/`
```console
ERROR: mysqld failed while attempting to check config
. . .
mysqld: Error on realpath() on '/var/lib/mysql-files' (Error 2 - No such file or directory)
```

**Comment by sharonsahadevan** [comment]
what is the configuration error?

**Comment by ltangvald** [comment]
For most Linux, systems, the default value of secure-file-priv is /var/lib/mysql-files.
However, for this image we set it to NULL as default: https://github.com/docker-library/mysql/blob/master/8.0/config/my.cnf#L26
Unless you have need of the secure-file-priv system, I suggest adding secure-file-priv=NULL to your mounted config files.

**Comment by wglambert** [comment]
Closing as this issue seems resolved

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by fredericrous** [comment]
I can reproduce the issue. Folder /etc/mysql is not mounted as expected. The folder is empty. Therefore my.cnf file is not present

**Comment by boay24** [comment]
3/11/2020  MySQL 8.0 confirm is not working 
 I'm facing a problem, I'v tried everything with no luck.
 (wsl2)
![image](https://user-images.githubusercontent.com/61148495/76413186-91900d00-63c7-11ea-851a-f41f7e719c04.png)

**Comment by yosifkit** [comment]
@boay24, if you are mounting a config from windows with `secure-file-priv` set (`-v C:/some/my.cnf:/etc/mysql/my.cnf`), then that might the problem.  See the warning a couple lines up: `[Warning] World-writable config file '/etc/mysql/my.cnf' is ignored`.  Since the only way to share things from Windows to Linux containers is for them to be world-writable permissions, you'll need to instead build an image with your config inside (and ensure `chmod` to the proper permissions). Or basically every config value from my.cnf is available as a flag, so just pass in the few that need changed (use `docker run -it --rm mysqld:8.0 --help --verbose` to see all the options and their current default values).

`docker run`:
```console
$ docker run -d -e MYSQL_ROOT_PASSWORD=secret mysql:8.0 --character-set-server=utf8mb4 [more-mysqld-flags]
```
docker-compose file:
```yaml
services:
  sql:
    image: mysql:8.0
    command:
      - '--character-set-server=utf8mb4'
      - --another-flag
```

Also note to not override the base `/etc/mysql/my.cnf` file (since it has some useful defaults) and instead put new config files into an included `conf.d` directory: https://github.com/docker-library/docs/tree/47056d4d6b95b70cd58d1d61671f1b7d338bfee5/mysql#using-a-custom-mysql-configuration-file
