### ISSUE TITLE
Using docker-compose [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist

### ISSUE THREAD

**Issue by andhika2as** [docker-library/mysql#551]
Issue Type: Question related to docker deployment.

Problem: Permission issue when mysql access local storage.

------------
I want to deploy wordpress with mysql and storage in local. 

The docker-compose.yml:
```
version: '3.7' 

services:

  db-mysql:
    image: mysql:5.7
    user: 999:999
    privileged: true 
    command: "--skip-grant-tables"
    volumes:
      - /data:/var/lib/mysql
    restart: always 
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD:Root123
      - MYSQL_DATABASE:shift-db
      - MYSQL_USER:mysql
      - MYSQL_PASSWORD:mySql123
    networks:
      - wordpress-net

  wordpress:
    depends_on:
      - db-mysql
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST:db-mysql
      - WORDPRESS_DB_USER:mysql
      - WORDPRESS_DB_PASSWORD:mySql123
      - WORDPRESS_DB_NAME:shift-db
    networks:
      - wordpress-net

networks:
  wordpress-net:

volumes:
  data:
     driver: local
```
I receive error in mysql container:
> db-mysql_1   | 2019-03-18T10:20:15.733850Z 0 [Warning] Can't open and lock time zone table: Table 'mysql.time_zone_leap_second' doesn't exist trying to live without them
> db-mysql_1   | 2019-03-18T10:20:15.734107Z 0 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
> db-mysql_1   | 2019-03-18T10:20:15.734374Z 0 [ERROR] Native table 'performance_schema'.'cond_instances' has the wrong structure
> [And more ERROR] with same 'wrong structure'

I use privileged: true & command: "--skip-grant-tables", becaue if not I got infinite reboot with error:
> db-mysql_1   | 2019-03-18T10:24:13.183102Z 0 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
> db-mysql_1   | 2019-03-18T10:24:13.183134Z 0 [ERROR] Fatal error: Failed to initialize ACL/grant/time zones structures or failed to remove temporary table files.
db-mysql_1   | 2019-03-18T10:24:13.183276Z 0 [ERROR] Aborting

EDIT: I also already chmod -R 777 /data & chown -r mysql:mysql /data

**Comment by wglambert** [comment]
<details>
<summary> docker-compose.yml </summary>

```yml
version: '3.7'

services:

  db-mysql:
    image: mysql:5.7
    user: 999:999
#    privileged: true 
#    command: "--skip-grant-tables"
    volumes:
      - /data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Root123
      MYSQL_DATABASE: shift-db
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mySql123
    networks:
      - wordpress-net

  wordpress:
    depends_on:
      - db-mysql
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db-mysql
      WORDPRESS_DB_USER: mysql
      WORDPRESS_DB_PASSWORD: mySql123
      WORDPRESS_DB_NAME: shift-db
    networks:
      - wordpress-net

networks:
  wordpress-net:

volumes:
  data:
     driver: local
```

</details>

<details>
<summary> docker-compose up </summary>

```console
$ docker-compose up
Creating network "mysql-551_wordpress-net" with the default driver
Creating volume "mysql-551_data" with local driver
Creating mysql-551_db-mysql_1 ... done
Creating mysql-551_wordpress_1 ... done
Attaching to mysql-551_db-mysql_1, mysql-551_wordpress_1
wordpress_1  | WordPress not found in /var/www/html - copying now...
db-mysql_1   | 2019-03-18T17:00:29.972999Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
db-mysql_1   | 2019-03-18T17:00:29.974013Z 0 [Note] mysqld (mysqld 5.7.23) starting as process 1 ...
wordpress_1  | Complete! WordPress has been successfully copied to /var/www/html
db-mysql_1   | 2019-03-18T17:00:29.976122Z 0 [Note] InnoDB: PUNCH HOLE support available
db-mysql_1   | 2019-03-18T17:00:29.976134Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db-mysql_1   | 2019-03-18T17:00:29.976137Z 0 [Note] InnoDB: Uses event mutexes
db-mysql_1   | 2019-03-18T17:00:29.976139Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
db-mysql_1   | 2019-03-18T17:00:29.976140Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
db-mysql_1   | 2019-03-18T17:00:29.976142Z 0 [Note] InnoDB: Using Linux native AIO
db-mysql_1   | 2019-03-18T17:00:29.976344Z 0 [Note] InnoDB: Number of pools: 1
db-mysql_1   | 2019-03-18T17:00:29.976437Z 0 [Note] InnoDB: Using CPU crc32 instructions
db-mysql_1   | 2019-03-18T17:00:29.993785Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
db-mysql_1   | 2019-03-18T17:00:30.005223Z 0 [Note] InnoDB: Completed initialization of buffer pool
db-mysql_1   | 2019-03-18T17:00:30.008091Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db-mysql_1   | 2019-03-18T17:00:30.020288Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
db-mysql_1   | 2019-03-18T17:00:30.115323Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
db-mysql_1   | 2019-03-18T17:00:30.115474Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db-mysql_1   | 2019-03-18T17:00:30.492372Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db-mysql_1   | 2019-03-18T17:00:30.494633Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
db-mysql_1   | 2019-03-18T17:00:30.494667Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
db-mysql_1   | 2019-03-18T17:00:30.495813Z 0 [Note] InnoDB: Waiting for purge to start
db-mysql_1   | 2019-03-18T17:00:30.546154Z 0 [Note] InnoDB: 5.7.23 started; log sequence number 12359978
db-mysql_1   | 2019-03-18T17:00:30.546656Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db-mysql_1   | 2019-03-18T17:00:30.547352Z 0 [Note] Plugin 'FEDERATED' is disabled.
db-mysql_1   | 2019-03-18T17:00:30.628218Z 0 [Note] InnoDB: Buffer pool(s) load completed at 190318 17:00:30
db-mysql_1   | 2019-03-18T17:00:30.754578Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
db-mysql_1   | 2019-03-18T17:00:30.798350Z 0 [Warning] CA certificate ca.pem is self signed.
db-mysql_1   | 2019-03-18T17:00:30.805111Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
db-mysql_1   | 2019-03-18T17:00:30.805205Z 0 [Note] IPv6 is available.
db-mysql_1   | 2019-03-18T17:00:30.805222Z 0 [Note]   - '::' resolves to '::';
db-mysql_1   | 2019-03-18T17:00:30.805257Z 0 [Note] Server socket created on IP: '::'.
db-mysql_1   | 2019-03-18T17:00:30.864601Z 0 [Warning] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db-mysql_1   | 2019-03-18T17:00:30.958525Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:30.958611Z 0 [Warning] 'user' entry 'mysql.session@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:30.958635Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:30.958715Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:30.958734Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:30.958761Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:31.036564Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:31.036617Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
db-mysql_1   | 2019-03-18T17:00:31.775136Z 0 [Note] Event Scheduler: Loaded 0 events
db-mysql_1   | 2019-03-18T17:00:31.775594Z 0 [Note] mysqld: ready for connections.
db-mysql_1   | Version: '5.7.23'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.3. Set the 'ServerName' directive globally to suppress this message
wordpress_1  | [Mon Mar 18 17:00:34.768687 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.12 configured -- resuming normal operations
wordpress_1  | [Mon Mar 18 17:00:34.768739 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

</details>

After setting up wordpress successfully through the webui:
```console
$ curl localhost:8080 | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html>
<html lang="en-US" class="no-js no-svg">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="profile" href="http://gmpg.org/xfn/11">

<script>(function(html){html.className = html.className.replace(/\bno-js\b/,'js')})(document.documentElement);</script>
<title>title &#8211; Just another WordPress site</title>
```

Seems to be some issue with your environment, are you using Docker for Mac/Windows?
I would try asking over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
