### ISSUE TITLE
MYSQL_ROOT_PASSWORD not working

### ISSUE THREAD

**Issue by brlebtag** [docker-library/mysql#557]
I'm trying to create the following database using docker-compose:

```
version: '3.1'
services:
mysql:
    image: mysql:5.7.21
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./dbs/mysql:/var/lib/mysql
```

my .env:

```
MYSQL_ROOT_PASSWORD=password
```

but when I run: **docker-compose up mysql**

it prints: 

```
mysql_1       | Initializing database
mysql_1       | 2019-04-06T23:10:49.591422Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
mysql_1       | 2019-04-06T23:10:51.593155Z 0 [Warning] InnoDB: New log files created, LSN=45790
mysql_1       | 2019-04-06T23:10:52.027557Z 0 [Warning] InnoDB: Creating foreign key constraint system tables.
mysql_1       | 2019-04-06T23:10:52.190840Z 0 [Warning] No existing UUID has been found, so we assume that this is the first time that this server has been started. Generating a new UUID: 39210408-58c1-11e9-8d8b-0242ac180002.
mysql_1       | 2019-04-06T23:10:52.216439Z 0 [Warning] Gtid table is not ready to be used. Table 'mysql.gtid_executed' cannot be opened.
mysql_1       | 2019-04-06T23:10:52.217204Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
```

my directory (ls -lah): 

```
-rw-r--r--  1 brlebtag bruno 1,5K Abr  6 20:10 docker-compose.yml
-rw-r--r--  1 brlebtag bruno  111 Abr  6 19:58 .env
```

my docker version (docker --version):
```
Docker version 18.09.4, build d14af54
```

my docker-compose version (docker-compose --version):
```
docker-compose version 1.24.0, build 0aa59064
```

 I don't know why...
