### ISSUE TITLE
MySQL 5.7 _FILE environment variables not loading

### ISSUE THREAD

**Issue by chris-atr** [docker-library/mysql#558]
Having numerous problems with _FILE environment variables when starting container.  Hard coding values (not using the _FILE types) works without any problems.  However, startup of MySQL appears to ignore most of the environment variables when used with the _FILE option.

**Steps to recreate:**

1. Create a handful of secret files to store sensative information.  In this case, I created the following files: mysql_root_pass.secret, mysql_user.secret, mysql_password.secret, mysql_dbname.secret, mysql_root_hosts.secret.  Populate these files with valid data.  Example: I populated mysql_user with, `myuser`, mysql_password with `mypassword`, mysql_dbname with `mydb`, and mysql_root_hosts with `%`

2. Create docker file as follows:
```
version: "3.7"
secrets:
  mysql_root_password:
    file: ./mysql_root_pass.secret
  mysql_user:
    file: ./mysql_user.secret
  mysql_password:
    file: ./mysql_password.secret
  mysql_db:
    file: ./mysql_dbname.secret
  mysql_hosts:
    file: ./mysql_root_hosts.secret
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    secrets:
      - mysql_root_password
      - mysql_user
      - mysql_password
      - mysql_db
      - mysql_hosts
    volumes:
      - "/home/me/docker/mysql/data:/var/lib/mysql"
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      TZ: America/New_York
      MYSQL_ROOT_HOST_FILE: /run/secrets/mysql_hosts
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_db
```
3. Start the container: `docker-compose up`).  When I do this, the following output is displayed:
```
Creating docker_mysql_1 ... done
Attaching to docker_mysql_1
mysql_1  | [Entrypoint] MySQL Docker Image 5.7.25-1.1.10
mysql_1  | [Entrypoint] No password option specified for new database.
mysql_1  | [Entrypoint]   A random onetime password will be generated.
mysql_1  | [Entrypoint] Initializing database
mysql_1  | [Entrypoint] Database initialized
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
mysql_1  | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
mysql_1  | [Entrypoint] GENERATED ROOT PASSWORD: DidYouReallyThinkIdPutItHere?
mysql_1  |
mysql_1  | [Entrypoint] ignoring /docker-entrypoint-initdb.d/*
mysql_1  |
mysql_1  | [Entrypoint] Server shut down
mysql_1  | [Entrypoint] Setting root user as expired. Password will need to be changed before database can be used.
mysql_1  |
mysql_1  | [Entrypoint] MySQL init process done. Ready for start up.
mysql_1  |
mysql_1  | [Entrypoint] Starting MySQL 5.7.25-1.1.10
```
4. Take note of the EntryPoint messages about not finding passwords.  It is not getting the environment variables that utilize files, correct?

5. You can access a bash prompt within the container using `docker exec -it ContainerID bash`.  Once inside, you will find that /run/secrets has the proper files, with the values you specified.  

6. Another test...I looked into MySQL list of databases (using mysql -u root and the temporary password).  The database specified in the MYSQL_DATABASE_FILE environment variable was not present.

7. Finally, review the list of environment variables (`printenv`), and you will find they are all there and pointing to the proper file locations.  

I'm sure I'm doing something wrong...but what is it?
