### ISSUE TITLE
MySQL user has no permissions, and "GRANT" statement is not permitted

### ISSUE THREAD

**Issue by kjaltana** [docker-library/mysql#577]
When creating a MySQL 5.7 container, the user is created but does not have any permissions. If you try to GRANT permissions, you receive the following errors:

`0 row(s) affected, 2 warning(s): 1285 MySQL is started in --skip-name-resolve mode; you must restart it without this switch for this grant to work 1287 Using GRANT statement to modify existing user's properties other than privileges is deprecated and will be removed in future release. Use ALTER USER statement for this operation.`

`ALTER USER` allows you to change everything except the user’s `GRANT `permissions.

Test Docker Command:

```
docker run --name mysql-test -e MYSQL_ROOT_PASSWORD=my-secret-pw \
     -e MYSQL_DATABASE=mytestdb -e MYSQL_USER=testuser \
     -e MYSQL_PASSWORD=testpassword --publish 3307:3306 -d mysql:5.7
```
Attach to the container, login as root to mysql with credentials , switch to the “mysql” database and run:

`select * from user where User = 'testuser'\G`

The query returns:

```
*************************** 1. row ***************************
                  Host: %
                  User: testuser
           Select_priv: N
           Insert_priv: N
           Update_priv: N
           Delete_priv: N
           Create_priv: N
             Drop_priv: N
           Reload_priv: N
         Shutdown_priv: N
          Process_priv: N
             File_priv: N
            Grant_priv: N
       References_priv: N
            Index_priv: N
            Alter_priv: N
          Show_db_priv: N
            Super_priv: N
 Create_tmp_table_priv: N
      Lock_tables_priv: N
          Execute_priv: N
       Repl_slave_priv: N
      Repl_client_priv: N
      Create_view_priv: N
        Show_view_priv: N
   Create_routine_priv: N
    Alter_routine_priv: N
      Create_user_priv: N
            Event_priv: N
          Trigger_priv: N
Create_tablespace_priv: N
              ssl_type:
            ssl_cipher:
           x509_issuer:
          x509_subject:
         max_questions: 0
           max_updates: 0
       max_connections: 0
  max_user_connections: 0
                plugin: mysql_native_password
 authentication_string: *9F69E47E519D9CA02116BF5796684F7D0D45F8FA
      password_expired: N
 password_last_changed: 2019-07-08 01:48:12
     password_lifetime: NULL
        account_locked: N
1 row in set (0.00 sec)
```
The same thing happens with this "docker-compose.yml" file:

```
version: "3.7"
services:
    mysql:
      image: mysql:5.7
      working_dir: /application
      volumes:
        - dbdata:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      networks:
        - web
      ports:
        - "${DB_PUBLIC_PORT}:3306"

    nginx:
      image: nginx:alpine
      restart: unless-stopped
      working_dir: /var/www
      tty: true
      volumes:
          - ./api:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - web
      ports:
       - "${FRONT_END_PORT}:80"

    php-fpm:
      build: ./phpdocker/php-fpm
      working_dir: /var/www
      depends_on:
        - mysql
      volumes:
        - ./api:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
      networks:
        - web

# Docker Networks
networks:
  web:
    driver: bridge

# Docker Volumes
volumes:
  dbdata: {}
```
