### ISSUE TITLE
Cant run mysql correctly

### ISSUE THREAD

**Issue by rikipm** [docker-library/mysql#596]
Im using docker for windows on windows 1903

My docker-compose.yml
```
db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOSTS: db
    ports:
      - "8080:80"
    depends_on:
      - db
```

After I trying to login in phpmyadmin, I see this

![Untitled](https://user-images.githubusercontent.com/13685393/65823691-afc3df80-e263-11e9-800b-4120d77af2bb.png)

`docker-compose logs db | grep Warning`:
```
 |?[0m 2019-09-28 22:47:36 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 22:47:36 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 22:47:36 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:28 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:38:35 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:38:50 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:25 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:40:32 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.3' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'user' entry 'root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'user' entry '@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:44 0 [Warning] 'proxies_priv' entry '@% root@2b37b2e63dbb' ignored in --skip-name-resolve mode.
?[36mdb_1          |?[0m 2019-09-28 23:45:53 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
?[36mdb_1          |?[0m 2019-09-28 23:46:15 10 [Warning] Aborted connection 10 to db: 'unconnected' user: 'unauthenticated' host: '172.21.0.4' (This connection closed normally without authentication)
```
[Full logs](https://pastebin.com/97xTdcWc)
