### ISSUE TITLE
Why is MYSQL_DATABASE env var being ignored by MySQL docker container?

### ISSUE THREAD

**Issue by ProggerPete** [docker-library/mysql#597]
I've got the following docker file:

```
version: "3.7"
services:
  db:
    container_name: db
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "mydb"
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./supplied/init:/docker-entrypoint-initdb.d/:ro
```

When I run 'docker-compose up' I get this in the logs:

> Recreating db ... done
> Attaching to db

If I check the available databases I see:

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| db                 |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
```

Why is the MYSQL_DATABASE env var being ignored?

I'm running on windows 10.

Thanks,
Pete

EDIT :

This looks like some sort of caching issue.  I changed the service name and container_name in the docker-compose file and it started working...  Is this the expected behaviour?  I have similar issues with running SQL scripts from within /docker-entrypoint-initdb.d.  They only seem to run the first time I call docker-compose up.  After that the result is cached, even if I run docker-compose up --force-recreate.
