### ISSUE TITLE
DBeaver: Could not create connection to database server

### ISSUE THREAD

**Issue by FuQiangZhang-Alex** [docker-library/mysql#612]
docker compose
```
# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
docker ps
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                          PORTS                               NAMES
5fd69f45bc69        mysql               "docker-entrypoint.s…"   14 seconds ago      Up 12 seconds                   0.0.0.0:3306->3306/tcp, 33060/tcp   mysql_db_1
8a9d1d8b4efa        adminer             "entrypoint.sh docke…"   12 minutes ago      Up 13 seconds                   0.0.0.0:8080->8080/tcp              mysql_adminer_1
c67e3d85f65f        postgres:10         "docker-entrypoint.s…"   10 months ago       Restarting (1) 37 seconds ago                                       alexfzhangapi_db_1
```
then I try to connect to it with DBeaver in the host using following info:
host: localhost
port: 3306
db: mysql
user: root
password: example

It gives me `Could not create connection to database server` error.
