### ISSUE TITLE
Attempting to set timezone using TZ causes 'Server returns invalid timezone'

### ISSUE THREAD

**Issue by techforge-peter** [docker-library/mysql#618]
I'm trying to set the timezone using the following in my docker-compose.yml.

 ```
 my-mysql:
    image: mysql:5.7.28
    container_name: my-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: something
      MYSQL_USER: something
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Australia/Sydney
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/:ro
```

After starting, attempts to connect to the database receive this error:

`Server returns invalid tiemzone. Go to 'Advanced' tab and set 'serverTimezone' property manually..`

I have verified that the container has the timezone set by running the following

```
docker exec my-mysql date
Thu Dec 19 23:17:51 AEDT 2019
```

How do I resolve this issue?

Thanks,
Peter
