### ISSUE TITLE
can not connect to mysql on network host by Navicat Premium 

### ISSUE THREAD

**Issue by xiaoxintang** [docker-library/mysql#620]
docker-compose.yaml 
```yaml
version: "3.7"
services: 
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    network_mode: host
    # ports: 
    #   - 3306:3306
    volumes: 
      - ./mysql:/var/lib/mysql
```
in container
![image](https://user-images.githubusercontent.com/24927686/71436730-b4484900-2729-11ea-861e-cef4baf18125.png)

### problem
i can connect to mysql using `Navicat Premium ` like this
```yaml
    # network_mode: host
    ports: 
      - 3306:3306
```
but i cant not connect to mysql while using network `host`
![image](https://user-images.githubusercontent.com/24927686/71436249-91b53080-2727-11ea-87c3-fec1e73dac96.png)
