### ISSUE TITLE
mysql container doesn't function properly on K8 cluster with NFS dynamic provisioning

### ISSUE THREAD

**Issue by vaskokj** [docker-library/mysql#647]
I've been trying to deploy Kubeflow on our test K8 cluster for the past week or so without much success. 

If you want the full story you can read this entire log of my debugging process (coming from someone who is new to this type of infrastructure). https://github.com/kubeflow/kubeflow/issues/4827

But to sum it up, with the nfs dynamic provisioner the mysql container won't start and throws an error of `mkdir: cannot create directory '/var/lib/mysql/': File exists` even though the NFS mount is in the container, and appears to be functioning properly.

For more details, this is what I found, and what I believe is the issue and I think its within the mysql docker container and how it interacts with nfs dynamic provisioning. 

First deploy the NFS dynamic provisioner to your K8 cluster via this https://github.com/kubernetes-incubator/external-storage/tree/master/nfs-client

While I don't know a lot about K8, I don't see how this has ever worked with dynamic provisioning (maybe specifically NFS only?).

I setup a MWE so I took the code snippets from here:

https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

`kubectl apply -f mysql-pvc.yaml`

I removed the VolumeClaim section as that is the entire intent of the dynamic provisioner. 

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: managed-nfs-storage  <--- THIS SHOULD MATCH  YOUR NFS STORAGECLASS
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

`kubectl apply -f mysql-deployment.yaml`
```
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        command: [ "/bin/sh", "-c", "sleep 100000" ]
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
```

```
kubectl get pv,pvc
NAME                                                        CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS          REASON   AGE
persistentvolume/mysql-pv-volume                            20Gi       RWO            Retain           Bound    default/mysql-pv-claim         managed-nfs-storage            5m16s

NAMESPACE      NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS          AGE
default        persistentvolumeclaim/mysql-pv-claim    Bound    mysql-pv-volume                            20Gi       RWO            managed-nfs-storage   5m27s
```

The pv was created automatically by the dynamic provisioner which is what is expected, however I get the following error when the mysql container tries to start up. 

```
$ kubectl logs mysql-7d7fdd478f-l2m8h
2020-03-05 18:26:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.47-1debian9 started.
2020-03-05 18:26:21+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2020-03-05 18:26:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 5.6.47-1debian9 started.
mkdir: cannot create directory '/var/lib/mysql/': File exists
```
This error stops the container from starting.

I went and deleted the deployment and started it up again but added  `command: [ "/bin/sh", "-c", "sleep 100000" ]` so the container would start and I could get into it to investigate

After getting into the container, the NFS mount is properly mounted and is writable, so the NFS Provisioner is doing what it should be doing.

```
# df -h | grep mysql
nfs1.example.com:/k8/default-mysql-pv-claim-pvc-0808d1bd-69ca-4ff5-825a-b846b1133e3a  1.0T  1.6G 1023G   1% /var/lib/mysql
```

If I create a "local" pv (avoiding the NFS)

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

and created the mysql deployment, the mysql pod starts up without issue.

This simply appears to be an issue with the mysql container trying to create the folder without the `-p` flag being passed to `mkdir` but I don't see anywhere in the CMD/ENTRYPOINT locations where it is calling `mkdir` without `-p`. 

Can anyone help me on solving this?

**Comment by wglambert** [comment]
So the oddity that I see is that in the entrypoint's [`docker_setup_env()`](https://github.com/docker-library/mysql/blob/d284e15821ac64b6eda1b146775bf4b6f4844077/5.6/docker-entrypoint.sh#L167-L184) function it checks for that folder to determine if there's an existing database `if [ -d "$DATADIR/mysql" ]; then DATABASE_ALREADY_EXISTS='true'`

So in your case it doesn't find it, but then tries to make it with the [`docker_create_db_directories()`](https://github.com/docker-library/mysql/blob/d284e15821ac64b6eda1b146775bf4b6f4844077/5.6/docker-entrypoint.sh#L134-L145) function and fails at `mkdir -p "$DATADIR"`
With `mkdir: cannot create directory '/var/lib/mysql/': File exists`

It feels like a permission issue somewhere, as was the case with some previous NFS issues https://github.com/docker-library/mariadb/issues/208#issuecomment-433546507, https://github.com/docker-library/mongo/issues/328#issuecomment-516586946 
Maybe including a `runAsUser: 999` and mounting the nfs folder as uid 999 might work as shown here https://github.com/docker-library/mongo/issues/328#issuecomment-516501046
```yaml
securityContext:
  runAsUser: 999
  fsGroup: 999
```
