### ISSUE TITLE
unable to create multi master replication setup 

### ISSUE THREAD

**Issue by mayankvaid88** [docker-library/mysql#681]
Hi All,

I am trying to setup multi master replication between two mysql containers. My current configurations are as below.

docker-compose.yml
```
version: '3'
services:
 
  ebs_login_db1:
    image: "mysql"
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - ./mysql/replication1.cnf:/etc/mysql/conf.d/replication1.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
  ebs_login_db2:
    image: "mysql"
    command: --init-file /data/application/init.sql
    volumes:
      - ./mysql/init.sql:/data/application/init.sql
      - ./mysql/replication2.cnf:/etc/mysql/conf.d/replication2.cnf
      - ./scripts/health_check.sh:/health_check.sh
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app_net
networks:
  app_net:
    driver: "bridge"
```

init.sql

```
SET SQL_LOG_BIN=0;
CREATE USER 'repl'@'%' IDENTIFIED BY 'password' REQUIRE SSL;
GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%';
FLUSH PRIVILEGES;
SET SQL_LOG_BIN=1;
CHANGE MASTER TO MASTER_USER='repl', MASTER_PASSWORD='password' FOR CHANNEL 'group_replication_recovery';
INSTALL PLUGIN group_replication SONAME 'group_replication.so';
```

Now when I run docker-compose and check the logs, I get below error
 

> Slave is not configured or failed to initialize properly. You must at least set --server-id to enable either a master or a slave. Additional error messages can be found in the MySQL error log..

Although I already have server_id = 1 and 2 in repliaction1.cnf and replication2.cnf respectively. Let me know if you require ".cnf" files.
It seems issue with init.sql as everything works good when I remove init.sql from docker-compose.yml.

Also please note that, manually I am able to setup the replication between the instances successfully following the same scripts as in init.sql
