### ISSUE TITLE
depolyment in Openshift for MySQL 

### ISSUE THREAD

**Issue by har2103** [docker-library/mysql#683]
Hi,

I am trying to deploy mysql:latest image in openshift. and created deployment config to deploy the pod.

<details> 
<summary> DeploymentConfig </summary>

```yaml
apiVersion: v1
kind: DeploymentConfig
metadata:
  generation: 1
  labels:
    openshift.io/deployment-config.name: mysql
  name: mysql-1
  namespace: dhhs-somhub-ait-mq-ns
spec:
  replicas: 0
  strategy:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi  
  selector:
    deployment: mysql-1
    deploymentconfig: mysql
    name: mysql
  template:
    metadata:
      labels:
        deployment: mysql-1
        deploymentconfig: mysql
        name: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: mysql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: mysql
          image: >-
            quay.state.mi.us/mdhhs/poc-repo:mysql
          imagePullPolicy: IfNotPresent
          name: mysql
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
              cpu: 2
            requests:
              memory: 1Gi
              cpu: 500m
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-1
```

</details>

After deployment i see below logs and container doesnt start. Is there anything am i missing?

```console
2020-06-18 19:07:20+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.20-1debian10 started.
--
  | 2020-06-18 19:07:20+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
  | 2020-06-18 19:07:21+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.20-1debian10 started.
  | 2020-06-18 19:07:21+00:00 [Note] [Entrypoint]: Initializing database files
  | 2020-06-18T19:07:21.100323Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
  | 2020-06-18T19:07:21.100439Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.20) initializing of server in progress as process 46
  | 2020-06-18T19:07:21.101964Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
  | 2020-06-18T19:07:21.101975Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
  | 2020-06-18T19:07:21.102042Z 0 [ERROR] [MY-010119] [Server] Aborting
  | 2020-06-18T19:07:21.102197Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.20)  MySQL Community Server - GPL.
```
