### ISSUE TITLE
Image can not be used from GH actions because "mysql_native_password" can not be set

### ISSUE THREAD

**Issue by mvorisek** [docker-library/mysql#690]
see https://stackoverflow.com/questions/60902904/how-to-pass-mysql-native-password-to-mysql-service-in-github-actions

This is a feature request to allow to set auth plugin from env var

**Comment by tianon** [comment]
Looking at https://github.community/t/job-service-command/16477/4, you should be able to get away with something like this (depending on where `options` gets injected in the `docker create` command):

```yaml
    services:
      mysql:
        image: mysql:8
        options: --entrypoint sh mysql:8 -c 'exec docker-entrypoint.sh --default-authentication-plugin=mysql_native_password' --
```

Other than that, this should be a feature request to GitHub Actions (IMO it's a huge oversight that job services cannot be started with a custom command, since that's a standard parameter for container configuration).
