### ISSUE TITLE
login mysql with password tips permission deniy

### ISSUE THREAD

**Issue by qiyongxiao** [docker-library/mysql#693]
Deploy mysql with k8s's statefulset, and the root password key MYSQL_ROOT_PASSWORD's value is from secrets, but while login to database, show permission denied. Please help me.
```
......
    spec:
      imagePullSecrets:
        - name: dockerpullimages
      containers:
        - image: harbor.imagicdatatech.com/magicdata/mysql:v5.7.22
          name: mysql
          ports:
            - name: mysql-port
              containerPort: 33306
          workingDir: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
#              value: fY4yVbBJQGkQNAHRHpYk5nXnfWFMMpGH
              valueFrom:
                secretKeyRef:
                  key: mysql_root.pw
                  name: mysql-root
...........
```
This is the secrets:
```
[qiyongxiao@k8smaster1 yamls]$ kubectl get secrets -n crowd mysql-root -o yaml
apiVersion: v1
data:
  mysql_root.pw: Zlk0eVZiQkpRR2tRTkFIUkhwWWs1blhuZldGTU1wR0gK
kind: Secret
metadata:
  name: mysql-root
  namespace: crowd
type: Opaque
```
decode the data:
```
[lsme@k8smaster1 yamls]$ echo "Zlk0eVZiQkpRR2tRTkFIUkhwWWs1blhuZldGTU1wR0gK" | base64 -d
fY4yVbBJQGkQNAHRHpYk5nXnfWFMMpGH
```
![image](https://user-images.githubusercontent.com/7349963/88164153-5390d880-cc46-11ea-8457-fc2223af102d.png)

Finaly, entry the pod to login database
```
root@mysql-0:/var/lib/mysql# mysql -uroot -pfY4yVbBJQGkQNAHRHpYk5nXnfWFMMpGH
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
root@mysql-0:/var/lib/mysql# echo $MYSQL_ROOT_PASSWORD
fY4yVbBJQGkQNAHRHpYk5nXnfWFMMpGH
```
![image](https://user-images.githubusercontent.com/7349963/88164443-b7b39c80-cc46-11ea-876f-477281065c5a.png)
