### ISSUE TITLE
utf8 dump imported as latin1

### ISSUE THREAD

**Issue by Levino** [docker-library/mysql#708]
I have an SQL dump in utf8 which I mount in `/docker-entrypoint-initdb.d`. The dump is successfully imported into the newly created database with charset utf8. However when I query the data, I get wrong characters. If I run the dump with MysqlAdmin or Datagrip all works fine. So it looks like during the import the client charset is latin1. How to change this?

Here is my docker-compose file:
```yaml
version: "3.8"
services:
  housing-project-database:
    image: library/mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_DATABASE: db258533
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db258533
      MYSQL_PASSWORD: XXX
    ports:
      - 3316:3306
    volumes:
      - ./sites/housing-project/database:/docker-entrypoint-initdb.d
```

Might be related to #201 .

**Comment by Levino** [comment]
I found a workaround by mounting a custom config file.
`docker-compose.yml`:
```yaml
version: "3.8"
services:
  housing-project:
    build:
      context: ./sites/housing-project
    volumes:
      - ./sites/housing-project/code:/kunden/258533_36433/webseiten/wohnprojekt-moehra
    depends_on:
      - housing-project-database
    environment:
      APACHE_DOCUMENT_ROOT: /kunden/258533_36433/webseiten/wohnprojekt-moehra
    ports:
      - 8080:80
  housing-project-database:
    image: library/mysql:5.6
    environment:
      MYSQL_DATABASE: db258533
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: db258533
      MYSQL_PASSWORD: XXX
    ports:
      - 3316:3306
    volumes:
      - ./sites/housing-project/database:/docker-entrypoint-initdb.d
      - ./sites/housing-project/config:/etc/mysql/conf.d
```
`./sites/housing-project/config/mysql.cnf`:
```
[client]
default_character_set           = utf8
[mysqld]
# charset and collation
character_set_server            = utf8
collation_server                = utf8_general_ci

Now all works fine, even though this is annoying. I personally find all this should be configurable via environment variables.
```
