### ISSUE TITLE
can't create mysql user and databases

### ISSUE THREAD

**Issue by kabunx** [docker-library/mysql#733]
# docker-compose.yml
```
version: '3'

services:
  ### MYSQL ################################################
  mysql:
    container_name: mysql
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=latest
        - TZ=${MYSQL_TIMEZONE}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - ${MYSQL_DATA_DIR:-/var/docker/volumes/mysql}:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - database
    restart: always

networks:
  database:
```

.env
```
# timezone
TIMEZONE=UTC
# mysql
MYSQL_VERSION=latest
MYSQL_USER=admin
MYSQL_PASSWORD=****
MYSQL_ROOT_PASSWORD=****
MYSQL_PORT=3306
MYSQL_ENTRYPOINT_INITDB=./mysql/initdb.d
MYSQL_DATA_DIR=/var/docker/volumes/mysql
```

# Dockerfile
```
FROM mysql:latest

#####################################
# Set Timezone
#####################################

ARG TZ=UTC
ENV TZ ${TZ}
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone && \
    chown -R mysql:root /var/lib/mysql/

COPY ./conf.d/my.cnf /etc/mysql/conf.d/my.cnf

RUN chmod 0444 /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]

EXPOSE 3306

```

./mysql/initdb.d/create_db.sql
```
CREATE DATABASE
IF NOT EXISTS `leading_crm` DEFAULT CHARSET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci';
GRANT ALL ON `leading_crm`.* TO 'admin'@'%';

FLUSH PRIVILEGES ;
```

docker-compose up -d

log
```
mysql      | 2020-12-03 09:24:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql      | 2020-12-03 09:24:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql      | 2020-12-03 09:24:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql      | 2020-12-03 09:24:45+00:00 [Note] [Entrypoint]: Initializing database files
mysql      | 2020-12-03T09:24:45.984143Z 0 [Warning] [MY-010915] [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql      | 2020-12-03T09:24:45.984211Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.22) initializing of server in progress as process 43
mysql      | 2020-12-03T09:24:45.998721Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql      | 2020-12-03T09:24:46.820108Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql      | 2020-12-03T09:24:48.453325Z 6 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
mysql      | 2020-12-03 09:24:51+00:00 [Note] [Entrypoint]: Database files initialized
mysql      | 2020-12-03 09:24:51+00:00 [Note] [Entrypoint]: Starting temporary server
mysql      | 2020-12-03T09:24:51.658803Z 0 [Warning] [MY-010915] [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql      | 2020-12-03T09:24:51.658922Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 88
mysql      | 2020-12-03T09:24:51.681137Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
mysql      | 2020-12-03T09:24:51.907102Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
mysql      | 2020-12-03T09:24:52.014851Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: /var/run/mysqld/mysqlx.sock
mysql      | 2020-12-03T09:24:52.134356Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
mysql      | 2020-12-03T09:24:52.134552Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
mysql      | 2020-12-03T09:24:52.137097Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
mysql      | 2020-12-03T09:24:52.161030Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.22'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
mysql      | 2020-12-03 09:24:52+00:00 [Note] [Entrypoint]: Temporary server started.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/iso3166.tab' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/leap-seconds.list' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/localtime/iso3166.tab' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/localtime/leap-seconds.list' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/localtime/localtime/iso3166.tab' as time zone. Skipping it.
mysql      | Warning: Unable to load '/usr/share/zoneinfo/localtime/localtime/localtime/leap-seconds.list' as time zone. Skipping it.
mysql      | ERROR 1406 (22001) at line 198328: Data too long for column 'Name' at row 1
mysql      | 2020-12-03 09:24:56+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql      | 2020-12-03 09:24:56+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql      | 2020-12-03 09:24:56+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql      | 2020-12-03T09:24:56.639399Z 0 [Warning] [MY-010915] [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql      | 2020-12-03T09:24:56.639520Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.22) starting as process 1
mysql      | 2020-12-03T09:24:56.650042Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
```

no user created and no database created!!!
