### ISSUE TITLE
Long line of container launch.

### ISSUE THREAD

**Issue by SinGlEBW** [docker-library/mysql#742]
I am facing a problem. I would like to control the scripts listed in the documentation
/ var / lib / mysql, /etc/mysql/conf.d, /docker-entrypoint-initdb.d.
But I have to enter a pancake line:

docker run --rm --name some-mysql1 -v $ {pwd} / server / config / mySQL / saveDB: / var / lib / mysql -v $ {pwd} /server/config/mySQL/conf.d:/ etc / mysql / conf.d -v $ {pwd} /server/config/mySQL/table:/docker-entrypoint-initdb.d -e MYSQL_ROOT_PASSWORD = secret -e MYSQL_DATABASE = test -d mysql: latest

How can I move all 3 points to one place so that you can specify a short entry

docker run --rm --name some-mysql1 -v $ {pwd} / server / config / mySQL: / setMysql -e MYSQL_ROOT_PASSWORD = secret -e MYSQL_DATABASE = test -d mysql: latest

setMysql / docker-entrypoint-initdb.d
setMysql / conf.d -v
setMysql / mysql

**Comment by wglambert** [comment]
Why not use a `docker-compose.yml` file? 

```yaml
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
    volumes:
      - ./server/config/mySQL/saveDB:/var/lib/mysql
      - ./server/config/mySQL/conf.d:/etc/mysql/conf.d
      - ./server/config/mySQL/table:/docker-entrypoint-initdb.d
```

I don't think there's a simple way to combine those directories into one without mounting a custom config file and doing other configuration. I would try asking over at [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
