### ISSUE TITLE
docker-composer mysql service keeps restarting

### ISSUE THREAD

**Issue by BinZhiZhu** [docker-library/mysql#745]
docker-composer.yml mysql config as follow：

```
 mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    # mysql太常用了，还是常规自动启动吧
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
```

docker-composer start mysql success,but mysql keeps restarting always：

```
5b1d54f2c30d   mysql:8.0                                  "docker-entrypoint.s…"   About a minute ago   Restarting (1) Less than a second ago
```

I checked the mysql logs as follow:

```
➜  docker docker-compose logs mysql
Attaching to docker_mysql_1
mysql_1          | 2021-03-01 13:54:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:54:23+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2021-03-01 13:54:23+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:05+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:10+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2021-03-01 13:55:10+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:28+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2021-03-01 13:55:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:43+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
mysql_1          | 2021-03-01 13:55:46+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql_1          | 2021-03-01 13:55:46+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
```

I can not fix this problem, What will be the problem？It was normal before I upgraded the docker version. Will it be related to upgrading the docker version?
