### ISSUE TITLE
thread_stack doesn't change (mysql 5.7.33)

### ISSUE THREAD

**Issue by RogerSik** [docker-library/mysql#756]
Extra (bind) mounted configuration file:

docker-compose.yml
```
   mysql:
     image: mysql:5.7
     volumes:
       - /etc/localtime:/etc/localtime:ro
       - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
     ports:
       - '3306:3306'
```

mysqld.cnf:
```
[mysqld]
bind-address = 0.0.0.0
performance_schema = ON

innodb_buffer_pool_size = 2G
innodb_flush_log_at_trx_commit = 0
innodb_log_buffer_size = 64M
innodb_log_file_size = 512M
innodb_flush_method = O_DIRECT
innodb_doublewrite = 0
innodb_lock_wait_timeout = 600

join_buffer_size=256K
table_open_cache=128

max_connections=10000
max_allowed_packet = 512M

# Higher value to fix: Thread stack overrun
thread_cache_size = 256
thread_stack      = 512K
```

After booting up:

```
mysql> SHOW GLOBAL VARIABLES LIKE '%stack%';mysql -e "SHOW GLOBAL VARIABLES LIKE 'thread_stack'
+----------------------------------------+--------+
| Variable_name                          | Value  |
+----------------------------------------+--------+
| performance_schema_max_statement_stack | 10     |
| thread_stack                           | 262144 |
+----------------------------------------+--------+
```
