### ISSUE TITLE
Get  "/dev/null: Permission denied" error at Docker Desktop 3.3.0

### ISSUE THREAD

**Issue by hungdh1405** [docker-library/mysql#760]
It still work normally at Docker Desktop 3.2.2
I just updated to Docker Desktop 3.3.0 then got this error :

![image](https://user-images.githubusercontent.com/24900497/114515949-1bfc0d80-9c67-11eb-98b8-7403ae60cd1d.png)

My environment information :
Macbook Pro 2019 - MacOS Big Sur ( 11.2.3 )
Docker Desktop for Mac : 3.3.0(62916)

My docker-compose : 

```
version: "3.7"
# define all services
services:
  mysql:
    image: "mysql:md"
    restart: "no"
    container_name: mysql_md
    ports:
      - "3306:3306"
      - "33060:33060"
    privileged: true
    build:
      context: ./
      dockerfile: dockerfile/mysql
    volumes:
      - "./data/conf/mysql:/etc/mysql/conf.d"
    environment:
      - MYSQL_ROOT_PASSWORD=XXXX
      - MYSQL_DATABASE=XXXX
      - MYSQL_USER=XXXX
      - MYSQL_PASSWORD=XXXXXX
      - MYSQL_ROOT_HOST=%
```

My docker file :

```
FROM mysql:latest
LABEL description="MySQL DB"
EXPOSE 3306
EXPOSE 33060
```
Anyone have this problem, please tell me how to fix !

Sorry for my poor English.
