### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by kofgokhan** [docker-library/mysql#766]
Hi,

I have this docker-compose file and when I start the containers it says Permission Denied for the mysql initialization scripts.
```console
db_1   | 2021-04-24 11:29:31+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/00-create.sql
db_1   | /usr/local/bin/docker-entrypoint.sh: line 75: /docker-entrypoint-initdb.d/00-create.sql: Permission denied
db_1 exited with code 1
```
```yaml
version: '3.8'

services:
    app:
        build: ./app
        restart: always
        ports:
            - 5000:5000
        volumes:
            - ./app:/usr/src/app
        
    db:
        build: ./db
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
```

Was working a couple of days ago. I have reset factory settings in dockers and rebuilt the images but still the same.
