### ISSUE TITLE
Host '172.18.0.1' is not allowed to connect to this MySQL server using docker compose 3.8 & mysql 8.0.24

### ISSUE THREAD

**Issue by UserSina** [docker-library/mysql#767]
**First of all**: This is not a duplicate of [this issue](https://github.com/docker-library/mysql/issues/275) since I'm using another version of `docker compose` (v3.8) and `mysql` (8.0.24) and the error is slightly different. (More details under Context below)

## 1. Versions:
Second of all, this doesn't happen on my _Windows 10_ machine:

```BASH
docker -v
# Docker version 20.10.5, build 55c4c88

docker-compose -v
# docker-compose version 1.29.0, build 07737305
```

It only happens on my **Ubuntu 20.04** machine:

```BASH
docker -v
# Docker version 20.10.6, build 370c289

docker-compose -v
# docker-compose version 1.29.1, build c34c88b2
```

## 2. Context:

I've looked into the [mentioned issue](https://github.com/docker-library/mysql/issues/275) and tried everything in there but nothing worked.
What worked however (very briefly) is the [following post](https://www.jeffgeerling.com/blog/2017/how-fix-host-1721801-not-allowed-connect-mysql-docker).
After using a mounted volume instead of the data volume, I was indeed able to test the connection from a `phpmyadmin` interface. However I got instantly redirected to the home screen with a  `Host '172.18.0.1' is not allowed...` error message. (right after clicking on a table)
I've tried re-building the image & deleting the mounted files but nothing succeeded in the end.

Here is my `docker-compose.yml` for a simple express app with a mysql database:
```YML
version: '3.8'

services:
  api-server:
    image: api-server
    build: ./server/
    env_file: ./server/config/dev.env
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 9000:9000
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - mysern-app
    container_name: my_express_app

  mysqldb:
    image: mysql:8.0.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myRootPassword
      MYSQL_DATABASE: db_to_appdy
      MYSQL_USER: user
      MYSQL_PASSWORD: myUserPassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/backup/:/mysql/backup
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - mysern-app
    ports:
      - 3306:3306
    container_name: my_mysql_app
networks:
  mysern-app:
    driver: bridge
volumes:
  mysql-data:
    driver: local
```

I've also noticed that the environment variables are not added (I've tried `SELECT host, user FROM mysql.user;` after starting a shell in the container and using the `mysql` command with no password)
Again, this happens only when running on **Ubuntu 20.04 focal** so far and not on my Windows 10 machine.
