### ISSUE TITLE
WSL2 --initialize specified but the data directory has files in it. Aborting.

### ISSUE THREAD

**Issue by Furman1331** [docker-library/mysql#771]
Hello, for a few months I use WSL2 on my computer. Now i need to use docker and i have that issue 
![pobrane (1)](https://user-images.githubusercontent.com/72356359/118297228-27e52480-b4de-11eb-9c16-82b50add124a.png)
I read some posts but nothing helps me.

Docker-compose file :
```yaml
version: '3'

networks:
    nginx-php74-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mysql8-service
        networks:
            - nginx-php74-mysql8-node

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:8
        container_name: mysql8-container
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        expose:
            - '3306'
        environment:
            MYSQL_DATABASE: "volleyball"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        networks:
            - nginx-php74-mysql8-node

    # node
    node-service:
        image: node:latest
        container_name: node-container
        volumes:
            - ./app:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php74-mysql8-node
```
Mysql dockerFile :  
```dockerfile
FROM ubuntu:latest

ENV locale-gen en_US.UTF-8

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server pwgen && rm -rf /var/lib/apt/lists/* –Setting up default database configuration
COPY my.cnf /etc/mysql/conf.d/my.cnf
COPY charset.cnf /etc/mysql/conf.d/charset.cnf

ADD startup.sh 96 /startup.sh

ENV MYSQL_USER=mysqladmin MYSQL_PASS=Random REPLICATION_MASTER=False REPLICATION_SLAVE=False REPLICATION_USER=replica REPLICATION_PASS=replica
–Configure mysql port
EXPOSE 3306

VOLUME ["/storage/mysql/data", “/var/lib/mysql”]

CMD ["/bin/bash","/startup.sh"]
```

Important lines of code : 
```console
--initialize specified but the data directory has files in it. Aborting.
 The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
```
