### ISSUE TITLE
docker insta exits after you attach a volume

### ISSUE THREAD

**Issue by Hasdino** [docker-library/mysql#784]
just as the title describes:

the error: 

`  [Server] /usr/sbin/mysqld (mysqld 8.0.26) initializing of server in progress as process 42
Server] --initialize specified but the data directory has files in it. Aborting.
Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
Server] Aborting
[Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.26)  MySQL Community Server - GPL. `

ive tried with psql works fine but with this image if the host is windows doesnt work and i cant find a solution

my code thus far  

```
version: "3.8"
services: 
  sql-server-db:
    container_name: sql-server-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "8080:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ********
    volumes:
    - dados:/var/lib/mysql/data
volumes:
  dados:
```
