### ISSUE TITLE
MYSQL_ROOT_PASSWORD not respected in docker-compose

### ISSUE THREAD

**Issue by Austio** [docker-library/mysql#796]
Hey there, thanks for this image.

I am running to an issue with setting up mysql with *no* volumes and *no* existing container.  I confirm this by removing the previous container when upping my container and not exposing a volume in the yml.  

### Reproduction

```
# Create a docker-compose.yml file
version: '3'
services:
  mysql:
    image: mysql:5.7.34
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=a_password
```

Up the container

```
docker-compose up mysql

#  mysql_1_85c85daa724c | 2021-10-31T12:42:15.966371Z 1 [Warning] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
```
