### ISSUE TITLE
Different result for docker-compose with mysql:latest and mysql:5.7

### ISSUE THREAD

**Issue by Edward-Zhou** [docker-library/mysql#802]
I am trying to create mysql with docker-compose, and I have docker-compose.yml below:
```
version: '3.9'
services:
    meekou-web:
        container_name: 'meekou-web'
        image: 'edward8520/meekou:web-v0.0.5'
        ports: 
            - "8888:80"
            - "8889:443"
        environment:
          - NODE_ENV=production
        #volumes:
        #  - ./meekou-web/:/usr/share/nginx/html
        expose:
          - "80"
          - "443"
    meekou-server:
        container_name: 'meekou-server'
        image: 'edward8520/meekou:server-v0.0.5'
        restart: always
        working_dir: '/app'
        ports: 
            - "8886:80"
            - "8887:443"
        volumes: 
        #    - ./meekou-server/:/app
            - ./meekou-certificates/https:/https/
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_KESTREL__ENDPOINTS__HTTP__URL=http://+:80
            - ASPNETCORE_KESTREL__ENDPOINTS__HTTPS__URL=http://+:443
            - ASPNETCORE_Kestrel__Certificates__Default__Password=test
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        entrypoint: 
            ["dotnet", "Meekou.Mango.Web.Host.dll"]           
        depends_on: 
            - meekou-mysql
            #- meekou-chrome
    #meekou-chrome:
    #    container_name: 'meekou-chrome'
    #    image: 'selenium/standalone-chrome'
    #    shm_size: 200m
    #    restart: always
    #    ports: 
    #         - "8886:4444"
    meekou-mysql:
        container_name: 'meekou-mysql'
        image: 'mysql'
        restart: always
        environment: 
            MYSQL_DATABASE: 'xxDb'
            MYSQL_ROOT_PASSWORD: 'xx'
            MYSQL_USER: 'xx'
            MYSQL_PASSWORD: 'xx'
        ports: 
          - "8880:3306"
        volumes: 
           - ./meekou-mysql:/var/lib/mysql
```
If I use image `mysql`, it fail to create the user which seems environment did not work.
If I use image `mysql:5.7`, it will successfully create the user.

And this issue only occures in CentOS, it did not happen on windows 10.
