### ISSUE TITLE
MYSQL_ALLOW_REMOTE_CONNECTION param to avoid: Unable to connect to dockerized mysql db remotely

### ISSUE THREAD

**Issue by jrichardsz** [docker-library/mysql#827]
Currently to allow remote connections we need to enter manually to the container and:

- modify /etc/mysql/my.cnf : bind-address = 0.0.0.0
- create a remote user

More details here
- https://stackoverflow.com/a/42091745/3957754
- https://stackoverflow.com/questions/35580488/unable-to-connect-to-dockerized-mysql-db-remotely

It would be awesome a new parameter like:

```
environment:
  MYSQL_ROOT_PASSWORD: changeme
  MYSQL_USER: john_doe
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: acme
  MYSQL_ALLOW_REMOTE_CONNECTION: true
```

Could you point me to some file in this repository to try to add this feature?

Thanks
