### ISSUE TITLE
Operation ALTER USER failed for 'root'@'%'

### ISSUE THREAD

**Issue by nickdnk** [docker-library/mysql#839]
Hello

I cannot get the server to reset the root user using the `docker-entrypoint-initdb.d/init.sql` file. This used to work and has now stopped working for reasons I don't understand. It's really frustrating. I'm not 100% sure this is the right place to report this, so please point me in the right direction if this is the wrong place.

I use the `mysql/mysql-server:8.0.27` image.

I start the container like this:

```
image: mysql/mysql-server:8.0.27
ports:
  - "3306:3306"
volumes:
  - type: bind
    source: ./mysql-init.sql
    target: /docker-entrypoint-initdb.d/init.sql
    read_only: true
environment:
  - MYSQL_ROOT_PASSWORD=secret
```

But when the container starts, it prints out:
```
ERROR 1396 (HY000) at line 1: Operation ALTER USER failed for 'root'@'%'`
```

The script contains:
```
ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
```

I just need to be able to connect to the container from anywhere using the default root user. Why is this so difficult? It used to work fine with MySQL 5.7, and I also had this config working with 8.0... but now it doesn't work and I didn't really change anything except update Docker.

I made sure to delete all containers and volumes just to make sure no lingering data is messing with this. Please advise.
