### ISSUE TITLE
docker compose command '--group-concat-max-len=-1' not work

### ISSUE THREAD

**Issue by ganluo960214** [docker-library/mysql#863]
```yaml
version: "3.8"

services:

    mysql5.7.38:
        restart: always
        image: mysql:5.7.38
        ports:
            - 3307:3306
        environment:
            MYSQL_ROOT_PASSWORD: 9eaf2e1b52404c8d83bf77102656013d
        volumes:
            - ./volumes/mysql5.7.38:/var/lib/mysql:rw
        command:
            - --group-concat-max-len=-1
            - --general_log=off
            - --general_log_file=/var/lib/mysql/general.log
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --lower_case_table_names=1
            - --slow_query_log=on
            - --long_query_time=1
            - --slow_query_log_file=/var/lib/mysql/mysql-slow.log
            - --skip-name-resolve
            - --sql-mode=NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

```bash
root@1933792550d5:/# mysqladmin variables -p | grep group_concat_max_len
Enter password:
| group_concat_max_len                                     | 1024
                                                                                                                                                                                   |
```
