### ISSUE TITLE
error checking context: no permission to read from directory

### ISSUE THREAD

**Issue by baravak** [docker-library/mysql#874]
pemission denided after rebuild mysql docker compose

`docker-compose.yml`
``` yml
version: "3.3"
mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
         MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
         MYSQL_DATABASE: $MYSQL_DATABASE
         MYSQL_USER: $MYSQL_USER
         MYSQL_PASSWORD: $MYSQL_PASSWORD
    volumes:
         - ./mysql:/var/lib/mysql
    ports:
         - 3306:3306
```
first build: `docker-compose up --build` => `is ok`
down and update sources: `docker-compose down` => `is oke`
try for rebuild: `docker-compose up --build` => `error`
```
error checking context: 'no permission to read from '/home/user/docker/mysql/#ib_16384_0.dblwr''.
ERROR: Service 'risloo_old' failed to build : Build failed
```
