### ISSUE TITLE
Since 8.0.29 : Operation not permitted on /docker-entrypoint-initdb.d 

### ISSUE THREAD

**Issue by lecajer** [docker-library/mysql#883]
On container startup I get 
`shippeo_mysql | ls: cannot access '/docker-entrypoint-initdb.d/': Operation not permitted`

When I rollback to `8.0.28` it is fine

Here's a part of the docker-compose.yml
```yml
   mysql:
        container_name: mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3307:3306
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        volumes:
            - mysql-data:/var/lib/mysql
```

Some keywords for those loking for help:
>SQLSTATE[HY000] [1130] Host '172.18.0.9' is not allowed to connect to this   
  MySQL server
  
>PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name does  
   not resolve
