### ISSUE TITLE
Max Connections

### ISSUE THREAD

**Issue by kaleb-keny** [docker-library/mysql#893]
Hi

I'm starting up a mysql server with docker-compose as per the below:

```
services:
version: '3.3'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=high_frequency
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
    ports:
      - '3311:3311'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
```
Can you tell me how I can increase MAX_CONNECTIONS with the same docker-compose.yaml file please?
I understand it's possible to do with with `Dockerfile`, but was wondering if it's possible to configure within the `docker-compose.yaml` file.

Thank you

**Comment by wglambert** [comment]
You can pass `--max_connections=1000` as the [command to the image](https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file), or supply a [`my.cnf`](https://github.com/docker-library/docs/tree/master/mysql#using-a-custom-mysql-configuration-file), or after initializing enter on the `mysql` command line `SET GLOBAL max_connections = 1000;` (which you could also have as a `.sql` script to be executed on initialization https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance)

**Comment by kaleb-keny** [comment]
Hey thank you for that, i've honestly been looking all over for an answer to this... i am worried of the situation where my server restarts for some reason and undoes the max_connections setting, and i will probably forget if i restart my docker instance to incorporate it into the cnf... so i guess a .sql script that runs on a recurrent bases and initialization is the only way.... thank you for your help

**Comment by yosifkit** [comment]
You can just add `command` to your docker-compose yaml and it'll be there when doing  `docker-compose up`.
```yaml
services:
  db:
    command: [ "--max_connections=1000" ]
```
