### ISSUE TITLE
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by Gabrielttbr** [docker-library/mysql#898]
Não estou conseguindo acessar meu container pelo workbench, e nem pelo container. No container colo o comando mysql -u root -p, mais sempre me retorna esse erro ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

Os container são gerenciados pelo docker-compose

```yaml
version: '3.7'
services:
  database:
    build: './database'
    container_name: database-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always     
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
  api:
    build: './'
    container_name: node_container
    restart: always
    environment:
      MYSQL_DATABASE: raizes
      MYSQL_PASSWORD: root
      MYSQL_USER: root
    
      MYSQL_PORT: 3307
    ports:
      - "9001:9001"
    depends_on:
      - database
```

Dockerfile do mysql
FROM mysql

Dockerfile da api
```dockerfile
FROM node:17.9.0
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm i

COPY . .

EXPOSE 3000

RUN npm i -g @nestjs/cli
RUN ls

CMD npm run start:dev
```
