### ISSUE TITLE
Unexpected value 'command' 

### ISSUE THREAD

**Issue by omaresmael** [docker-library/mysql#900]
Hey guys
I have an issue. 
I'm not sure what is wrong with my yml file so it doesn't expect a command

here is my yml snippet 

```
services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: cpm_cypress_tests
          MYSQL_USER: mysqluser
          MYSQL_PASSWORD: secret
        command: --log-bin-trust-function-creators=ON
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    defaults:
      run:
        working-directory: ${{ matrix.path }}
```

is there something I'm missing?! 

thank you <3

**Comment by wglambert** [comment]
`env` should be [`environment`](https://docs.docker.com/compose/compose-file/#environment) and the `defaults:` service is both unaligned and not a service? And `options:` isn't found in the compose specification https://docs.docker.com/compose/compose-file/

Otherwise it works fine
```yml
services:
      mysql:
        image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: cpm_cypress_tests
          MYSQL_USER: mysqluser
          MYSQL_PASSWORD: secret
        command: --log-bin-trust-function-creators=ON
        ports:
          - 33306:3306
 ```

```console
$ docker-compose up -d
Creating network "mysql_default" with the default driver
Pulling mysql (mysql:8.0)...
8.0: Pulling from library/mysql
e54b73e95ef3: Pull complete
327840d38cb2: Pull complete
642077275f5f: Pull complete
e077469d560d: Pull complete
cbf214d981a6: Pull complete
f4fda5f8b9a8: Pull complete
a41c2763043b: Pull complete
f86b3df6abb1: Pull complete
95b1c2ed2ecf: Pull complete
b0edcd52771b: Pull complete
a3d312b5c835: Pull complete
Digest: sha256:657d78ee56e09101902673adcdd7d2bf03012e759c1aa525eeca28cb0fe1aa7d
Status: Downloaded newer image for mysql:8.0
Creating mysql_mysql_1 ... done

$ docker exec -it mysql_mysql_1 mysql -umysqluser -psecret
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 8
Server version: 8.0.30 MySQL Community Server - GPL

Copyright (c) 2000, 2022, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
```

If you need further help you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum
