### ISSUE TITLE
Docker images missing the mysqlimport binary

### ISSUE THREAD

**Issue by bryjohns** [docker-library/mysql#901]
I would like to use mysqlimport to load data for a project on a docker container. It appears the mysql docker images do not have that utility. I'm assuming mysqlimport is not part of the "mysql-community-server-minimal" package.

How would I add mysqlimport back to the image? Is there an image or option to use "mysql-community-server" instead of "mysql-community-server-minimal"?

**Comment by wglambert** [comment]
[This image](https://hub.docker.com/_/mysql) has `mysqlimport`

```console
$ docker run --rm mysql which mysqlimport
/usr/bin/mysqlimport
```

There's also an alternative way to import data (on first initialization) https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance

**Comment by bryjohns** [comment]
I'm using the following docker-compose file with docker version 20.10.17 on MacOs. I deleted the containers, images, and volumes and re-composed. I was using image tag mysql:5.7 and switched to mysql.

```
version: '3.3'

services:
   db:
     image: mysql
     volumes:
       - db_data:/var/lib/mysql
       - ./config/conf.d/:/etc/mysql/conf.d/
     restart: always
     ...
```

Which isn't installed on the image:  
/usr/local/bin/docker-entrypoint.sh: line 400: exec: which: not found

When I click open in terminal from Docker Desktop:  
```
sh-4.4# ls /usr/bin/mysql*
/usr/bin/mysql				/usr/bin/mysql_upgrade
/usr/bin/mysql-secret-store-login-path	/usr/bin/mysqladmin
/usr/bin/mysql_config			/usr/bin/mysqldump
/usr/bin/mysql_migrate_keyring		/usr/bin/mysqlpump
/usr/bin/mysql_ssl_rsa_setup		/usr/bin/mysqlsh
/usr/bin/mysql_tzinfo_to_sql
```
