### ISSUE TITLE
Using data persistence in docker with mysql 8.0 and above causes failure to initialize DD storage engine

### ISSUE THREAD

**Issue by mustansirgodhrawala** [docker-library/mysql#914]
Error Logs
```
db                      | 2022-09-05T18:15:09.033251Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
db                      | 2022-09-05T18:15:09.240816Z 1 [ERROR] [MY-012960] [InnoDB] Cannot create redo log files because data files are corrupt or the database was not shut down cleanly after creating the data files.
db                      | 2022-09-05T18:15:09.626593Z 1 [ERROR] [MY-010334] [Server] Failed to initialize DD Storage Engine
db                      | 2022-09-05T18:15:09.627740Z 0 [ERROR] [MY-010020] [Server] Data Dictionary initialization failed.
db                      | 2022-09-05T18:15:09.628522Z 0 [ERROR] [MY-010119] [Server] Aborting
db                      | 2022-09-05T18:15:09.647968Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.30)  MySQL Community Server - GPL.
```

Compose File Used
```yaml
mysql:
    image: mysql:8.0.30
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./data/db:/var/lib/mysql
    container_name: db
```

I've replaced some env vars for this post.
