### ISSUE TITLE
setting `binlog_expire_logs_seconds` with docker-compose

### ISSUE THREAD

**Issue by kaleb-keny** [docker-library/mysql#918]
Hi,

I'm starting up a mysql server with docker-compose as per the below, but i :

```
services:
version: '3.3'
services:
  db:
    command: ["--max_connections=5000"]
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=high_frequency
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
    ports:
      - '3311:3311'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
```

But I also would like to set `binlog_expire_logs_seconds` to 86400 seconds, would the below be the way to achieve this outcome?

```
services:
version: '3.3'
services:
  db:
    command: ["--max_connections=5000","--binlog_expire_logs_second=86400"]
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=high_frequency
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
    ports:
      - '3311:3311'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
```

Thank you

**Comment by kaleb-keny** [comment]
I guess this is the way
```
services:
version: '3.3'
services:
  db:
    command: 
      - ["--max_connections=5000"]
      - ["--binlog_expire_logs_second=86400"]        
    image: mysql:8.0
    cap_add:"--binlog_expire_logs_second=86400"
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=high_frequency
      - MYSQL_ROOT_PASSWORD=XXXXXXXXX
    ports:
      - '3311:3311'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local
```
as per the  post [here](https://stackoverflow.com/questions/58535964/how-to-configure-mysql-instance-with-multiline-command-flag-in-docker-compose-ym)

**Comment by yosifkit** [comment]
Both ways are valid for providing a list in yaml, and so either should work:
```yaml
    command: ["--max_connections=5000", "--binlog_expire_logs_second=86400"]
# or
    command: 
      - "--max_connections=5000"
      - "--binlog_expire_logs_second=86400"
```
