### ISSUE TITLE
Bug on MySQL container startup when using MYSQL_ALLOW_EMPTY_PASSWORD

### ISSUE THREAD

**Issue by vincentchalamon** [docker-library/mysql#92]
When using `MYSQL_ALLOW_EMPTY_PASSWORD` environment variable in my _docker-compose.yml_ configuration, MySQL is unable to restart because of following error:
> MySQL init process in progress...
> …
> Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
> Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
> 2015-08-18 15:51:19 60 [Warning] 'proxies_priv' entry '@ root@default' ignored in --skip-name-resolve mode.
> Enter password: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

I don't have the problem when using a password. Here is my _docker-compose.yml_ configuration:
```yml
web:
    build: .
    volumes:
        - .:/var/www
    net: "host"
    tty: true

db:
    image: mysql
    command: mysqld --port 3386
    net: "host"
    environment:
        MYSQL_DATABASE: api
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: yes
```

I didn't have this problem a few weeks ago, I just reset my docker environment.
