### ISSUE TITLE
Unable to connect to database when setting container name as user host inside docker dridge network

### ISSUE THREAD

**Issue by b-Tomas** [docker-library/mysql#935]
I have a docker compose file similar to the following, with a init.sql file that sets up the databases and users. When using `CREATE USER IF NOT EXISTS `user`@`%` IDENTIFIED WITH etc etc` and then setting grants for database and tables there is not problem, and when setting the user as  ``user`@`172.22.0.3``, which is the container IP, there is no problem either. When trying to set the user as ``chatbot_dev`@`webook`` (the container name), I get `Access denied for user 'user'@'172.22.0.3' (using password: YES)`, so the IP is being resolved from the name webhook but for some reason the user has no access.
```
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    networks:
      - whatsapp
    volumes:
      - db-data:/var/lib/mysql
      - ${PWD}/db/:/docker-entrypoint-initdb.d/
  webhook:
    image: my image
    networks:
      - whatsapp
    depends_on:
      - "db"
networks:
  whatsapp:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.1/16 
          gateway: 172.22.0.1
```
EXPECTED BEHAVIOUR: The container should be able to connect when setting the host for a user as the name of a container in the same network, following docker best practices
ACTUAL BEHAVIOUR: Access denied with container name, but able to connect when directly using the IP (which is not static)  or wildcard (insecure, as anyone would be able to access via the exposed port with the password)

Is there any solution to this, or am I doing something wrong?
