### ISSUE TITLE
"--initialize specified but the data directory has files in it"

### ISSUE THREAD

**Issue by blabut** [docker-library/mysql#945]
I am facing a issue trying to use mysql as part of a Docker compose setup. My problem is similar to the one described in https://github.com/docker-library/mysql/issues/757 but not the same since it occurs even when I am not trying to set up any volume. Nevertheless, I tried most of the suggested solutions without any success at solving this problem.
Here are the details from my problem, mainly copied/pasted from the [StackOverflow post](https://stackoverflow.com/questions/75405333/issue-with-mysql-in-docker-compose-on-mac) I opened yesterday:

I have an issue when trying to use a `mysql` docker container as part of a `docker-compose` on my MacBook (`2,6 GHz 6-Core Intel Core i7` under `Ventura 13.0.1`). Here is what my `docker-compose.yml` file looks like:
```
version: '3.1'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - 3306
    healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER} --password=${MYSQL_PASSWORD}
            interval: 5s
            timeout: 5s
            retries: 55
    restart: unless-stopped
  flask:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    command: python3 app.py
    depends_on:
      - "db"
    restart: unless-stopped
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/var/www/html
    ports:
      - 80:80
    depends_on:
      - "flask"
    restart: unless-stopped
```

When trying to run `docker-compose up`, the mysql container crashes, and I get the following error in the logs:
```
compose_2023-db-1  | 2023-02-09T22:33:31.523197Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
compose_2023-db-1  | 2023-02-09T22:33:31.523257Z 0 [ERROR] [MY-010119] [Server] Aborting
compose_2023-db-1  | 2023-02-09T22:33:31.523345Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32)  MySQL Community Server - GPL.
```
As visible in my `docker-compose.yml`, I am not even trying to persist the database in a volume. I have actually tried, both using host file system and a docker volume, with the exact same error each time. 
I have tried restarting Docker, my computer, updating Docker, removing all images and containers without success. I also tried several tags for `mysql` images (namely `latest`, `7.6` and `8.0`) with the same result.
What really bugs me is that this exact same setup used to work fine until earlier today, but I am not able to tell what action caused it to start erroring out every time. More strangely, I can run a `mysql` container with a similar setup from with the following command:
```docker run --name mysql \
-e MYSQL_ROOT_PASSWORD=root \
-e MYSQL_DATABASE=db \
-e MYSQL_USER=myuser \
-e MYSQL_PASSWORD=mypass \
-v $(pwd)/db:/var/lib/mysql \
-p 3306:3306 \
mysql:5.7
```

Thanks a lot for any help !
