### ISSUE TITLE
heredoc bash error

### ISSUE THREAD

**Issue by doertedev** [docker-library/mysql#96]
I really hope I'm overseeing something obvious here:

Pulled both 5.6 and 5.7 without changes and built it on my trolovo, docker compose having the rootpw, db, user + pw as env settings, boot it up and both give me the following error msgs:

```
mysql_1 | /entrypoint.sh: line 101: warning: here-document at line 47 delimited by end-of-file (wanted `EOSQL')
mysql_1 | /entrypoint.sh: line 102: syntax error: unexpected end of file 
mysql_1 exited with code 2
```

Can someone enlighten me? Maybe I'm just high on caffeine again.

**Comment by doertedev** [comment]
Edge infos: 

[I] app-emulation/docker
     Installed versions:  1.8.1^si(14:13:35 26.08.2015)(device-mapper lxc -apparmor -aufs -btrfs -experimental -overlay)

[I] app-emulation/docker-compose
     Installed versions:  1.4.0(12:04:33 04.09.2015)(-test PYTHON_TARGETS="python2_7")

docker-compose.yml:

```yml
mysql:
  image: doerty/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: asdf
    MYSQL_USER: asdf
    MYSQL_PASSWORD: asdf
  volumes:
    - ../docker/mysql/data/:/var/lib/mysql/
```
built via:
`docker build -f ./mysql/Dockerfile --force-rm=true -q --rm=true mysql`
(Without a volume it doesn't work either).
