### ISSUE TITLE
Host connect to mysql container

### ISSUE THREAD

**Issue by rosskevin** [docker-library/mysql#98]
I'm using docker-compose with a `-p` for designating discrete CI build environments.  I am looping, attempting to connect to mysql to wait until it is ready for requests.

docker-compose.yml snippet

```yaml
db:
  image: library/mysql:5.7.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
```

I start the server with `docker-compose -p 112 up -d db` (where `112` is the build number), and have no problems there if I check the logs or bash in and connect.

From the host, I attempt to find the IP using `docker inspect --format '{{ .NetworkSettings.IPAddress }}' 112_db_1` and get `172.17.0.104`.

If I try to connect from host -> container with `172.17.0.104` with `mysql -h"172.17.0.104" -u"root"` it hangs.  If I try to connect with `mysql -h"192.168.99.100" -u"root"`

Since I'm trying to dynamically determine the IP address as there will be concurrent containers for different builds, why does the `172` address not work?  What do I need to do to properly connect to the IP listed by the container?
